var express = require('express');
var router = express.Router();

/* GET users listing. */
router.post('/web/v1/sso/getResources', function(req, res, next) {
  res.send({
    "aasUserPrincipal": {
      "aasUserResources": {
        "resources": [
          {
            "description": "动态路由首页面",
            "displayOrder": 0,
            "iconUrl": "",
            "levelStructure": "",
            "linkUrl": "/upp/web/v1/allRoutes",
            "menuLevel": 1,
            "parentLevelStructure": "",
            "parentResourceid": "",
            "resourceDisplayName": "动态路由首页面",
            "resourceId": "212",
            "resourceName": "getAllRoutes",
            "resourceType": "api"
          },
          {
            "description": "查询单条静态路由详情",
            "displayOrder": 0,
            "iconUrl": "",
            "levelStructure": "",
            "linkUrl": "/upp/web/v1/staticRoute",
            "menuLevel": 1,
            "parentLevelStructure": "",
            "parentResourceid": "",
            "resourceDisplayName": "查询单条静态路由详情",
            "resourceId": "220",
            "resourceName": "getStaticRoute",
            "resourceType": "api"
          },
          {
            "description": "",
            "displayOrder": 0,
            "iconUrl": "",
            "levelStructure": "",
            "linkUrl": "/upp/web/v1/channelAbility",
            "menuLevel": 1,
            "parentLevelStructure": "",
            "parentResourceid": "",
            "resourceDisplayName": "编辑通道公司信息",
            "resourceId": "204",
            "resourceName": "patchChannelAbility",
            "resourceType": "api"
          },
          {
            "description": "查询所有codetable以及bankTypeCode、agencyCode、channelCode",
            "displayOrder": 0,
            "iconUrl": "",
            "levelStructure": "",
            "linkUrl": "/upp/web/v1/allCodetables",
            "menuLevel": 1,
            "parentLevelStructure": "",
            "parentResourceid": "",
            "resourceDisplayName": "查询所有codetable以及bankTypeCode、agencyCode、channelCode",
            "resourceId": "209",
            "resourceName": "getAllCodetables",
            "resourceType": "api"
          },
          {
            "description": "根据参数查询路由信息",
            "displayOrder": 0,
            "iconUrl": "",
            "levelStructure": "",
            "linkUrl": "/upp/web/v1/routes",
            "menuLevel": 1,
            "parentLevelStructure": "",
            "parentResourceid": "",
            "resourceDisplayName": "根据参数查询路由信息",
            "resourceId": "217",
            "resourceName": "getRoutes",
            "resourceType": "api"
          },
          {
            "description": "查看本方账户详情",
            "displayOrder": 0,
            "iconUrl": "",
            "levelStructure": "",
            "linkUrl": "/upp/web/v1/account",
            "menuLevel": 1,
            "parentLevelStructure": "",
            "parentResourceid": "",
            "resourceDisplayName": "查看本方账户详情",
            "resourceId": "201",
            "resourceName": "getAccount",
            "resourceType": "api"
          },
          {
            "description": "删除一条路由信息操作",
            "displayOrder": 0,
            "iconUrl": "",
            "levelStructure": "",
            "linkUrl": "/upp/web/v1/route",
            "menuLevel": 1,
            "parentLevelStructure": "",
            "parentResourceid": "",
            "resourceDisplayName": "删除一条路由信息操作",
            "resourceId": "214",
            "resourceName": "deleteRoute",
            "resourceType": "api"
          },
          {
            "description": "查看計費信息详情",
            "displayOrder": 0,
            "iconUrl": "",
            "levelStructure": "",
            "linkUrl": "/upp/web/v1/channelFee",
            "menuLevel": 1,
            "parentLevelStructure": "",
            "parentResourceid": "",
            "resourceDisplayName": "查看計費信息详情",
            "resourceId": "206",
            "resourceName": "getChannelFeeDetails",
            "resourceType": "api"
          },
          {
            "description": "新增一条静态路由",
            "displayOrder": 0,
            "iconUrl": "",
            "levelStructure": "",
            "linkUrl": "/upp/web/v1/staticRoute",
            "menuLevel": 1,
            "parentLevelStructure": "",
            "parentResourceid": "",
            "resourceDisplayName": "新增一条静态路由",
            "resourceId": "222",
            "resourceName": "postStaticRoute",
            "resourceType": "api"
          },
          {
            "description": "分页查询节假日",
            "displayOrder": 0,
            "iconUrl": "",
            "levelStructure": "",
            "linkUrl": "/upp/web/v1/holidays",
            "menuLevel": 1,
            "parentLevelStructure": "",
            "parentResourceid": "",
            "resourceDisplayName": "分页查询节假日",
            "resourceId": "211",
            "resourceName": "getHolidays",
            "resourceType": "api"
          },
          {
            "description": "删除一条静态路由信息",
            "displayOrder": 0,
            "iconUrl": "",
            "levelStructure": "",
            "linkUrl": "/upp/web/v1/staticRoute",
            "menuLevel": 1,
            "parentLevelStructure": "",
            "parentResourceid": "",
            "resourceDisplayName": "删除一条静态路由信息",
            "resourceId": "219",
            "resourceName": "deleteStaticRoute",
            "resourceType": "api"
          },
          {
            "description": "查询单个通道公司能力信息",
            "displayOrder": 0,
            "iconUrl": "",
            "levelStructure": "",
            "linkUrl": "/upp/web/v1/channelAbility",
            "menuLevel": 1,
            "parentLevelStructure": "",
            "parentResourceid": "",
            "resourceDisplayName": "查询单个通道公司能力信息",
            "resourceId": "203",
            "resourceName": "getChannelAbility",
            "resourceType": "api"
          },
          {
            "description": "新增-编辑-删除-修改计费信息",
            "displayOrder": 0,
            "iconUrl": "",
            "levelStructure": "",
            "linkUrl": "/upp/web/v1/channelFee",
            "menuLevel": 1,
            "parentLevelStructure": "",
            "parentResourceid": "",
            "resourceDisplayName": "新增-编辑-删除-修改计费信息",
            "resourceId": "208",
            "resourceName": "getPatchDeteleUppChannelFeeDetails",
            "resourceType": "api"
          },
          {
            "description": "新增一条路由信息操作",
            "displayOrder": 0,
            "iconUrl": "",
            "levelStructure": "",
            "linkUrl": "/upp/web/v1/route",
            "menuLevel": 1,
            "parentLevelStructure": "",
            "parentResourceid": "",
            "resourceDisplayName": "新增一条路由信息操作",
            "resourceId": "216",
            "resourceName": "postRoute",
            "resourceType": "api"
          },
          {
            "description": "查询首页显示的总条数",
            "displayOrder": 0,
            "iconUrl": "",
            "levelStructure": "",
            "linkUrl": "/upp/web/v1/uppCounts",
            "menuLevel": 1,
            "parentLevelStructure": "",
            "parentResourceid": "",
            "resourceDisplayName": "查询首页显示的总条数",
            "resourceId": "224",
            "resourceName": "getUppCounts",
            "resourceType": "api"
          },
          {
            "description": "返回给前端的信息",
            "displayOrder": 0,
            "iconUrl": "",
            "levelStructure": "",
            "linkUrl": "/upp/web/v1/feeRoute",
            "menuLevel": 1,
            "parentLevelStructure": "",
            "parentResourceid": "",
            "resourceDisplayName": "返回给前端的信息",
            "resourceId": "213",
            "resourceName": "getFeeRoute",
            "resourceType": "api"
          },
          {
            "description": "更新静态路由信息",
            "displayOrder": 0,
            "iconUrl": "",
            "levelStructure": "",
            "linkUrl": "/upp/web/v1/staticRoute",
            "menuLevel": 1,
            "parentLevelStructure": "",
            "parentResourceid": "",
            "resourceDisplayName": "更新静态路由信息",
            "resourceId": "221",
            "resourceName": "patchStaticRoute",
            "resourceType": "api"
          },
          {
            "description": "分页查询所有通道公司信息",
            "displayOrder": 0,
            "iconUrl": "",
            "levelStructure": "",
            "linkUrl": "/upp/web/v1/channelAbilitys",
            "menuLevel": 1,
            "parentLevelStructure": "",
            "parentResourceid": "",
            "resourceDisplayName": "分页查询所有通道公司信息",
            "resourceId": "205",
            "resourceName": "getChannelAbilitys",
            "resourceType": "api"
          },
          {
            "description": "查询多种codetable",
            "displayOrder": 0,
            "iconUrl": "",
            "levelStructure": "",
            "linkUrl": "/upp/web/v1/codetables",
            "menuLevel": 1,
            "parentLevelStructure": "",
            "parentResourceid": "",
            "resourceDisplayName": "查询多种codetable",
            "resourceId": "210",
            "resourceName": "getCodetables",
            "resourceType": "api"
          },
          {
            "description": "查询所有的静态路由信息（分页）",
            "displayOrder": 0,
            "iconUrl": "",
            "levelStructure": "",
            "linkUrl": "/upp/web/v1/allStaticRoutes",
            "menuLevel": 1,
            "parentLevelStructure": "",
            "parentResourceid": "",
            "resourceDisplayName": "查询所有的静态路由信息（分页）",
            "resourceId": "218",
            "resourceName": "getAllStaticRoutes",
            "resourceType": "api"
          },
          {
            "description": "查看所有本方账户",
            "displayOrder": 0,
            "iconUrl": "",
            "levelStructure": "",
            "linkUrl": "/upp/web/v1/accounts",
            "menuLevel": 1,
            "parentLevelStructure": "",
            "parentResourceid": "",
            "resourceDisplayName": "查看所有本方账户",
            "resourceId": "202",
            "resourceName": "getAccounts",
            "resourceType": "api"
          },
          {
            "description": "修改一条路由信息操作",
            "displayOrder": 0,
            "iconUrl": "",
            "levelStructure": "",
            "linkUrl": "/upp/web/v1/route",
            "menuLevel": 1,
            "parentLevelStructure": "",
            "parentResourceid": "",
            "resourceDisplayName": "修改一条路由信息操作",
            "resourceId": "215",
            "resourceName": "patchRoute",
            "resourceType": "api"
          },
          {
            "description": "分页查询所有计费信息",
            "displayOrder": 0,
            "iconUrl": "",
            "levelStructure": "",
            "linkUrl": "/upp/web/v1/channelFees",
            "menuLevel": 1,
            "parentLevelStructure": "",
            "parentResourceid": "",
            "resourceDisplayName": "分页查询所有计费信息",
            "resourceId": "207",
            "resourceName": "getChannelFees",
            "resourceType": "api"
          },
          {
            "description": "根据参数查询静态路由信息",
            "displayOrder": 0,
            "iconUrl": "",
            "levelStructure": "",
            "linkUrl": "/upp/web/v1/staticRoutes",
            "menuLevel": 1,
            "parentLevelStructure": "",
            "parentResourceid": "",
            "resourceDisplayName": "根据参数查询静态路由信息",
            "resourceId": "223",
            "resourceName": "getStaticRoutes",
            "resourceType": "api"
          },
          {
            "description": "编辑",
            "displayOrder": 0,
            "iconUrl": "",
            "levelStructure": "",
            "linkUrl": "/upp/communications.html/edit",
            "menuLevel": 0,
            "parentLevelStructure": "",
            "parentResourceid": "",
            "resourceDisplayName": "编辑",
            "resourceId": "228",
            "resourceName": "communicationsHtmlEdit",
            "resourceType": "button"
          },
          {
            "description": "保存",
            "displayOrder": 0,
            "iconUrl": "",
            "levelStructure": "",
            "linkUrl": "/upp/communication-detail.html/save",
            "menuLevel": 0,
            "parentLevelStructure": "",
            "parentResourceid": "",
            "resourceDisplayName": "保存",
            "resourceId": "230",
            "resourceName": "communicationDetailHtmlSave",
            "resourceType": "button"
          },
          {
            "description": "查询",
            "displayOrder": 0,
            "iconUrl": "",
            "levelStructure": "",
            "linkUrl": "/upp/communications.html/query",
            "menuLevel": 0,
            "parentLevelStructure": "",
            "parentResourceid": "",
            "resourceDisplayName": "查询",
            "resourceId": "227",
            "resourceName": "communicationsHtmlQuery",
            "resourceType": "button"
          },
          {
            "description": "计费信息-编辑",
            "displayOrder": 0,
            "iconUrl": "",
            "levelStructure": "",
            "linkUrl": "/upp/charg-info.html/edit",
            "menuLevel": 0,
            "parentLevelStructure": "",
            "parentResourceid": "",
            "resourceDisplayName": "编辑",
            "resourceId": "238",
            "resourceName": "chargInfoHtmlEdit",
            "resourceType": "button"
          },
          {
            "description": "新增",
            "displayOrder": 0,
            "iconUrl": "",
            "levelStructure": "",
            "linkUrl": "/upp/static-rout.html/add",
            "menuLevel": 1,
            "parentLevelStructure": "",
            "parentResourceid": "",
            "resourceDisplayName": "新增",
            "resourceId": "95",
            "resourceName": "staticRoutHtmlAdd",
            "resourceType": "button"
          },
          {
            "description": "取消",
            "displayOrder": 0,
            "iconUrl": "",
            "levelStructure": "",
            "linkUrl": "/upp/edit-rout.html/cancel",
            "menuLevel": 1,
            "parentLevelStructure": "",
            "parentResourceid": "",
            "resourceDisplayName": "取消",
            "resourceId": "92",
            "resourceName": "editRoutHtmlCancel",
            "resourceType": "button"
          },
          {
            "description": "新增",
            "displayOrder": 0,
            "iconUrl": "",
            "levelStructure": "",
            "linkUrl": "/upp/smart-rout.html/add",
            "menuLevel": 1,
            "parentLevelStructure": "",
            "parentResourceid": "",
            "resourceDisplayName": "新增",
            "resourceId": "84",
            "resourceName": "smartRoutHtmlAdd",
            "resourceType": "button"
          },
          {
            "description": "保存",
            "displayOrder": 0,
            "iconUrl": "",
            "levelStructure": "",
            "linkUrl": "/upp/new-smart-rout.html/save",
            "menuLevel": 1,
            "parentLevelStructure": "",
            "parentResourceid": "",
            "resourceDisplayName": "保存",
            "resourceId": "89",
            "resourceName": "newSmartRoutHtmlSave",
            "resourceType": "button"
          },
          {
            "description": "删除",
            "displayOrder": 0,
            "iconUrl": "",
            "levelStructure": "",
            "linkUrl": "/upp/static-rout.html/delete",
            "menuLevel": 1,
            "parentLevelStructure": "",
            "parentResourceid": "",
            "resourceDisplayName": "删除",
            "resourceId": "97",
            "resourceName": "staticRoutHtmlDelete",
            "resourceType": "button"
          },
          {
            "description": "查询",
            "displayOrder": 0,
            "iconUrl": "",
            "levelStructure": "",
            "linkUrl": "/upp/static-rout.html/query",
            "menuLevel": 1,
            "parentLevelStructure": "",
            "parentResourceid": "",
            "resourceDisplayName": "查询",
            "resourceId": "94",
            "resourceName": "staticRoutHtmlQuery",
            "resourceType": "button"
          },
          {
            "description": "删除",
            "displayOrder": 0,
            "iconUrl": "",
            "levelStructure": "",
            "linkUrl": "/upp/smart-rout.html/delete",
            "menuLevel": 1,
            "parentLevelStructure": "",
            "parentResourceid": "",
            "resourceDisplayName": "删除",
            "resourceId": "86",
            "resourceName": "smartRoutHtmlDelete",
            "resourceType": "button"
          },
          {
            "description": "保存",
            "displayOrder": 0,
            "iconUrl": "",
            "levelStructure": "",
            "linkUrl": "/upp/edit-rout.html/save",
            "menuLevel": 1,
            "parentLevelStructure": "",
            "parentResourceid": "",
            "resourceDisplayName": "保存",
            "resourceId": "91",
            "resourceName": "editRoutHtmlSave",
            "resourceType": "button"
          },
          {
            "description": "取消",
            "displayOrder": 0,
            "iconUrl": "",
            "levelStructure": "",
            "linkUrl": "/upp/new-static-rout.html/cancel",
            "menuLevel": 1,
            "parentLevelStructure": "",
            "parentResourceid": "",
            "resourceDisplayName": "取消",
            "resourceId": "99",
            "resourceName": "newStaticStaticRoutHtmlCancel",
            "resourceType": "button"
          },
          {
            "description": "查询",
            "displayOrder": 0,
            "iconUrl": "",
            "levelStructure": "",
            "linkUrl": "/upp/smart-rout.html/query",
            "menuLevel": 1,
            "parentLevelStructure": "",
            "parentResourceid": "",
            "resourceDisplayName": "查询",
            "resourceId": "83",
            "resourceName": "smartRoutHtmlQuery",
            "resourceType": "button"
          },
          {
            "description": "取消",
            "displayOrder": 0,
            "iconUrl": "",
            "levelStructure": "",
            "linkUrl": "/upp/new-smart-rout.html/cancel",
            "menuLevel": 1,
            "parentLevelStructure": "",
            "parentResourceid": "",
            "resourceDisplayName": "取消",
            "resourceId": "88",
            "resourceName": "newSmartSmartRoutHtmlCancel",
            "resourceType": "button"
          },
          {
            "description": "编辑",
            "displayOrder": 0,
            "iconUrl": "",
            "levelStructure": "",
            "linkUrl": "/upp/static-rout.html/edit",
            "menuLevel": 1,
            "parentLevelStructure": "",
            "parentResourceid": "",
            "resourceDisplayName": "编辑",
            "resourceId": "96",
            "resourceName": "staticRoutHtmlEdit",
            "resourceType": "button"
          },
          {
            "description": "编辑",
            "displayOrder": 0,
            "iconUrl": "",
            "levelStructure": "",
            "linkUrl": "/upp/smart-rout.html/edit",
            "menuLevel": 1,
            "parentLevelStructure": "",
            "parentResourceid": "",
            "resourceDisplayName": "编辑",
            "resourceId": "85",
            "resourceName": "smartRoutHtmlEdit",
            "resourceType": "button"
          },
          {
            "description": "支付平台",
            "displayOrder": 1,
            "iconUrl": "",
            "levelStructure": "1.0.0",
            "linkUrl": "/upp/",
            "menuLevel": 3,
            "parentLevelStructure": "",
            "parentResourceid": "",
            "resourceDisplayName": "支付平台",
            "resourceId": "81",
            "resourceName": "upp",
            "resourceType": "menu"
          },
          {
            "description": "智能路由",
            "displayOrder": 1,
            "iconUrl": "",
            "levelStructure": "1.1.0",
            "linkUrl": "/upp/smart-rout.html",
            "menuLevel": 3,
            "parentLevelStructure": "1.0.0",
            "parentResourceid": "",
            "resourceDisplayName": "智能路由",
            "resourceId": "82",
            "resourceName": "smartRoutHtml",
            "resourceType": "menu"
          },
          {
            "description": "新增智能路由",
            "displayOrder": 1,
            "iconUrl": "",
            "levelStructure": "1.1.1",
            "linkUrl": "/upp/new-smart-rout.html",
            "menuLevel": 3,
            "parentLevelStructure": "1.1.0",
            "parentResourceid": "",
            "resourceDisplayName": "新增智能路由",
            "resourceId": "87",
            "resourceName": "newSmartSmartRoutHtmlCancel",
            "resourceType": "menu"
          },
          {
            "description": "编辑路由",
            "displayOrder": 2,
            "iconUrl": "",
            "levelStructure": "1.1.2",
            "linkUrl": "/upp/edit-rout.html",
            "menuLevel": 3,
            "parentLevelStructure": "1.1.0",
            "parentResourceid": "",
            "resourceDisplayName": "编辑路由",
            "resourceId": "90",
            "resourceName": "editRoutHtml",
            "resourceType": "menu"
          },
          {
            "description": "静态路由",
            "displayOrder": 2,
            "iconUrl": "",
            "levelStructure": "1.2.0",
            "linkUrl": "/upp/static-rout.html",
            "menuLevel": 3,
            "parentLevelStructure": "1.0.0",
            "parentResourceid": "",
            "resourceDisplayName": "静态路由",
            "resourceId": "93",
            "resourceName": "staticRoutHtml",
            "resourceType": "menu"
          },
          {
            "description": "新增静态路由",
            "displayOrder": 1,
            "iconUrl": "",
            "levelStructure": "1.2.1",
            "linkUrl": "/upp/new-static-rout.html",
            "menuLevel": 3,
            "parentLevelStructure": "1.2.0",
            "parentResourceid": "",
            "resourceDisplayName": "新增静态路由",
            "resourceId": "98",
            "resourceName": "newStaticStaticRoutHtml",
            "resourceType": "menu"
          },
          {
            "description": "查询本方账户信息",
            "displayOrder": 3,
            "iconUrl": "",
            "levelStructure": "1.3.0",
            "linkUrl": "/upp/local-account.html",
            "menuLevel": 3,
            "parentLevelStructure": "1.0.0",
            "parentResourceid": "",
            "resourceDisplayName": "查询本方账户信息",
            "resourceId": "225",
            "resourceName": "getLocalAccount",
            "resourceType": "menu"
          },
          {
            "description": "通道公司信息",
            "displayOrder": 4,
            "iconUrl": "",
            "levelStructure": "1.4.0",
            "linkUrl": "/upp/communications.html",
            "menuLevel": 3,
            "parentLevelStructure": "1.0.0",
            "parentResourceid": "",
            "resourceDisplayName": "通道公司信息",
            "resourceId": "226",
            "resourceName": "communicationsHtml",
            "resourceType": "menu"
          },
          {
            "description": "通道公司信息详情",
            "displayOrder": 1,
            "iconUrl": "",
            "levelStructure": "1.4.1",
            "linkUrl": "/upp/communication-detail.html",
            "menuLevel": 3,
            "parentLevelStructure": "1.4.0",
            "parentResourceid": "",
            "resourceDisplayName": "通道公司信息详情",
            "resourceId": "229",
            "resourceName": "communicationDetailHtml",
            "resourceType": "menu"
          },
          {
            "description": "计费信息",
            "displayOrder": 6,
            "iconUrl": "",
            "levelStructure": "1.6.0",
            "linkUrl": "/upp/charg-info.html",
            "menuLevel": 3,
            "parentLevelStructure": "1.0.0",
            "parentResourceid": "",
            "resourceDisplayName": "计费信息",
            "resourceId": "235",
            "resourceName": "chargeInfoHtml",
            "resourceType": "menu"
          }
        ],
        "roles": [
          {
            "appID": "upp_website",
            "appRoleID": "6",
            "roleName": "申请岗",
            "roleType": "2",
            "status": "0"
          }
        ]
      },
      "cacheKey": "",
      "currentUrl": "",
      "ssoLoginTime": "",
      "ssoTicket": "",
      "ssoUserEmail": "uppTreatment@wanda.cn",
      "ssoUserId": "1",
      "ssoUserImAccount": "liukai",
      "ssoUserMobile": "13000000001",
      "ssoUserName": "刘经办",
      "ssoUserOrgId": "1",
      "statusCode": "",
      "statusMessage": ""
    },
    "loginUrl": "http://10.213.57.216:8082/aas/v1/auth/loginurl?appId=upp_website&appSsoUrl=http%3A%2F%2F10.213.42.246%3A9090%2Fupp%2Fweb%2Fv1%2Fsso%2Flogin",
    "respHeader": {
      "respCode": "AAS-10000",
      "respMessage": "成功"
    }
  });
});

router.get('/web/v1/uppCounts', function(req, res, next) {
  res.send({
    respHeader: {
      respCode: 'UPP-10000'
    },
    uppCounts: {
      uppAccountsCounts: 20
    }
  });
});

router.get('/web/v1/allCodetables', function(req, res, next) {
  res.send({
    "respHeader": {
      "serviceName": null,
      "respMessage": "成功",
      "sessionId": "1462461678582",
      "reqId": "1471930736343",
      "respCode": "UPP-10000",
      "resMessageExt": null
    },
    "uppCodetableList": [
      {
        "codeType": "busType",
        "code": "0",
        "codeDesc": "信贷",
        "description": "业务类型"
      },
      {
        "codeType": "busType",
        "code": "1",
        "codeDesc": "保理",
        "description": "业务类型"
      },
      {
        "codeType": "busType",
        "code": "2",
        "codeDesc": "财富",
        "description": "业务类型"
      },
      {
        "codeType": "accountStatus",
        "code": "0",
        "codeDesc": "正常",
        "description": "账户状态"
      },
      {
        "codeType": "accountStatus",
        "code": "1",
        "codeDesc": "销户",
        "description": "账户状态"
      },
      {
        "codeType": "accountStatus",
        "code": "2",
        "codeDesc": "冻结",
        "description": "账户状态"
      },
      {
        "codeType": "accountProperty",
        "code": "0",
        "codeDesc": "收支",
        "description": "收支属性"
      },
      {
        "codeType": "accountProperty",
        "code": "1",
        "codeDesc": "收入",
        "description": "收支属性"
      },
      {
        "codeType": "accountProperty",
        "code": "2",
        "codeDesc": "支出",
        "description": "收支属性"
      },
      {
        "codeType": "accountType",
        "code": "0",
        "codeDesc": "对私/对公",
        "description": "账户类型（属性）"
      },
      {
        "codeType": "accountType",
        "code": "1",
        "codeDesc": "对私",
        "description": "账户类型（属性）"
      },
      {
        "codeType": "accountType",
        "code": "2",
        "codeDesc": "对公",
        "description": "账户类型（属性）"
      },
      {
        "codeType": "channelStatus",
        "code": "1",
        "codeDesc": "启用",
        "description": "通道状态"
      },
      {
        "codeType": "channelStatus",
        "code": "2",
        "codeDesc": "失效",
        "description": "通道状态"
      },
      {
        "codeType": "interfaceType",
        "code": "0",
        "codeDesc": "单笔/批量",
        "description": "接口类型"
      },
      {
        "codeType": "interfaceType",
        "code": "1",
        "codeDesc": "单笔",
        "description": "接口类型"
      },
      {
        "codeType": "interfaceType",
        "code": "2",
        "codeDesc": "批量",
        "description": "接口类型"
      },
      {
        "codeType": "windowType",
        "code": "0",
        "codeDesc": "全天(含节假日和休息日)",
        "description": "交易受理窗口类型"
      },
      {
        "codeType": "windowType",
        "code": "1",
        "codeDesc": "全天(不含节假日和休息日)",
        "description": "交易受理窗口类型"
      },
      {
        "codeType": "windowType",
        "code": "2",
        "codeDesc": "自定义每日受理时间（含节假日和休息日）",
        "description": "交易受理窗口类型"
      },
      {
        "codeType": "windowType",
        "code": "3",
        "codeDesc": "自定义每日受理时间（不含节假日和休息日）",
        "description": "交易受理窗口类型"
      },
      {
        "codeType": "recordStatus",
        "code": "0",
        "codeDesc": "启用",
        "description": "记录状态"
      },
      {
        "codeType": "recordStatus",
        "code": "1",
        "codeDesc": "注销/停用",
        "description": "记录状态"
      },
      {
        "codeType": "recordStatus",
        "code": "2",
        "codeDesc": "新增待审核",
        "description": "记录状态"
      },
      {
        "codeType": "recordStatus",
        "code": "3",
        "codeDesc": "修改待审核",
        "description": "记录状态"
      },
      {
        "codeType": "recordStatus",
        "code": "4",
        "codeDesc": "删除待审核",
        "description": "记录状态"
      },
      {
        "codeType": "applyStatus",
        "code": "0",
        "codeDesc": "已保存未提交",
        "description": "申请状态"
      },
      {
        "codeType": "applyStatus",
        "code": "1",
        "codeDesc": "已提交待审核",
        "description": "申请状态"
      },
      {
        "codeType": "applyStatus",
        "code": "2",
        "codeDesc": "审核通过",
        "description": "申请状态"
      },
      {
        "codeType": "applyStatus",
        "code": "3",
        "codeDesc": "审核拒绝",
        "description": "申请状态"
      },
      {
        "codeType": "cardType",
        "code": "0",
        "codeDesc": "本行同城及异地/他行",
        "description": "卡种"
      },
      {
        "codeType": "cardType",
        "code": "1",
        "codeDesc": "本行同城",
        "description": "卡种"
      },
      {
        "codeType": "cardType",
        "code": "2",
        "codeDesc": "本行异地",
        "description": "卡种"
      },
      {
        "codeType": "cardType",
        "code": "3",
        "codeDesc": "他行",
        "description": "卡种"
      },
      {
        "codeType": "isSameCity",
        "code": "0",
        "codeDesc": "异地",
        "description": "是否同城"
      },
      {
        "codeType": "isSameCity",
        "code": "1",
        "codeDesc": "同城",
        "description": "是否同城"
      },
      {
        "codeType": "feeType",
        "code": "0",
        "codeDesc": "手续费",
        "description": "计费类型"
      },
      {
        "codeType": "feeType",
        "code": "1",
        "codeDesc": "汇划费",
        "description": "计费类型"
      },
      {
        "codeType": "caculateType",
        "code": "0",
        "codeDesc": "按笔收费",
        "description": "收费计算方式"
      },
      {
        "codeType": "caculateType",
        "code": "1",
        "codeDesc": "按比例%收费",
        "description": "收费计算方式"
      },
      {
        "codeType": "operateType",
        "code": "0",
        "codeDesc": "新增",
        "description": "操作类型"
      },
      {
        "codeType": "operateType",
        "code": "1",
        "codeDesc": "修改",
        "description": "操作类型"
      },
      {
        "codeType": "operateType",
        "code": "2",
        "codeDesc": "删除",
        "description": "操作类型"
      },
      {
        "codeType": "holidayType",
        "code": "1",
        "codeDesc": "普通休息日",
        "description": "假日类型"
      },
      {
        "codeType": "holidayType",
        "code": "2",
        "codeDesc": "元旦",
        "description": "假日类型"
      },
      {
        "codeType": "holidayType",
        "code": "3",
        "codeDesc": "春节",
        "description": "假日类型"
      },
      {
        "codeType": "holidayType",
        "code": "4",
        "codeDesc": "清明节",
        "description": "假日类型"
      },
      {
        "codeType": "holidayType",
        "code": "5",
        "codeDesc": "劳动节",
        "description": "假日类型"
      },
      {
        "codeType": "holidayType",
        "code": "6",
        "codeDesc": "端午节",
        "description": "假日类型"
      },
      {
        "codeType": "holidayType",
        "code": "7",
        "codeDesc": "抗战胜利日",
        "description": "假日类型"
      },
      {
        "codeType": "holidayType",
        "code": "8",
        "codeDesc": "中秋节",
        "description": "假日类型"
      },
      {
        "codeType": "holidayType",
        "code": "9",
        "codeDesc": "国庆节",
        "description": "假日类型"
      },
      {
        "codeType": "holidayType",
        "code": "10",
        "codeDesc": "其他",
        "description": "假日类型"
      },
      {
        "codeType": "transStatus",
        "code": "0",
        "codeDesc": "处理中",
        "description": "交易状态"
      },
      {
        "codeType": "transStatus",
        "code": "1",
        "codeDesc": "成功",
        "description": "交易状态"
      },
      {
        "codeType": "transStatus",
        "code": "2",
        "codeDesc": "失败",
        "description": "交易状态"
      },
      {
        "codeType": "transStatus",
        "code": "3",
        "codeDesc": "未知",
        "description": "交易状态"
      },
      {
        "codeType": "settleType",
        "code": "0",
        "codeDesc": "实时",
        "description": "时效性（结算周期）"
      },
      {
        "codeType": "settleType",
        "code": "1",
        "codeDesc": "准实时",
        "description": "时效性（结算周期）"
      },
      {
        "codeType": "settleType",
        "code": "2",
        "codeDesc": "T+1",
        "description": "时效性（结算周期）"
      },
      {
        "codeType": "urgSupport",
        "code": "0",
        "codeDesc": "否",
        "description": "是否支持加急"
      },
      {
        "codeType": "urgSupport",
        "code": "1",
        "codeDesc": "是",
        "description": "是否支持加急"
      },
      {
        "codeType": "jobStatus",
        "code": "0",
        "codeDesc": "未执行",
        "description": "任务状态"
      },
      {
        "codeType": "jobStatus",
        "code": "1",
        "codeDesc": "执行中",
        "description": "任务状态"
      },
      {
        "codeType": "jobStatus",
        "code": "2",
        "codeDesc": "已执行",
        "description": "任务状态"
      },
      {
        "codeType": "maintainType",
        "code": "0",
        "codeDesc": "通道能力维护审核",
        "description": "待审核单据类型"
      },
      {
        "codeType": "maintainType",
        "code": "1",
        "codeDesc": "计费维护审核",
        "description": "待审核单据类型"
      },
      {
        "codeType": "maintainType",
        "code": "2",
        "codeDesc": "路由信息审核",
        "description": "待审核单据类型"
      },
      {
        "codeType": "maintainType",
        "code": "3",
        "codeDesc": "静态路由信息维护",
        "description": "待审核单据类型"
      },
      {
        "codeType": "amountSection",
        "code": "0",
        "codeDesc": "0",
        "description": "金额分段"
      },
      {
        "codeType": "amountSection",
        "code": "1",
        "codeDesc": "1000",
        "description": "金额分段"
      },
      {
        "codeType": "amountSection",
        "code": "2",
        "codeDesc": "5000",
        "description": "金额分段"
      },
      {
        "codeType": "amountSection",
        "code": "3",
        "codeDesc": "10000",
        "description": "金额分段"
      },
      {
        "codeType": "amountSection",
        "code": "4",
        "codeDesc": "30000",
        "description": "金额分段"
      },
      {
        "codeType": "amountSection",
        "code": "5",
        "codeDesc": "50000",
        "description": "金额分段"
      },
      {
        "codeType": "amountSection",
        "code": "6",
        "codeDesc": "100000",
        "description": "金额分段"
      },
      {
        "codeType": "amountSection",
        "code": "7",
        "codeDesc": "500000",
        "description": "金额分段"
      },
      {
        "codeType": "amountSection",
        "code": "8",
        "codeDesc": "1000000",
        "description": "金额分段"
      },
      {
        "codeType": "amountSection",
        "code": "9",
        "codeDesc": "1000000000000",
        "description": "金额分段"
      },
      {
        "codeType": "priorityCode",
        "code": "1",
        "codeDesc": "高",
        "description": "优先级"
      },
      {
        "codeType": "priorityCode",
        "code": "2",
        "codeDesc": "普通",
        "description": "优先级"
      },
      {
        "codeType": "productType",
        "code": "0",
        "codeDesc": "收/付款",
        "description": "产品类型"
      },
      {
        "codeType": "productType",
        "code": "1",
        "codeDesc": "付款",
        "description": "产品类型"
      },
      {
        "codeType": "productType",
        "code": "2",
        "codeDesc": "扣款",
        "description": "产品类型"
      },
      {
        "codeType": "recordStatusDisplay",
        "code": "0",
        "codeDesc": "启用",
        "description": "记录状态"
      },
      {
        "codeType": "recordStatusDisplay",
        "code": "1",
        "codeDesc": "注销/停用",
        "description": "记录状态"
      },
      {
        "codeType": "uppChannelCode",
        "code": "99BILL",
        "codeDesc": "快钱公司",
        "description": "通道信息"
      },
      {
        "codeType": "uppChannelCode",
        "code": "ABC",
        "codeDesc": "中国农业银行",
        "description": "通道信息"
      },
      {
        "codeType": "uppChannelCode",
        "code": "BOC",
        "codeDesc": "中国银行",
        "description": "通道信息"
      },
      {
        "codeType": "uppChannelCode",
        "code": "CCB",
        "codeDesc": "中国建设银行",
        "description": "通道信息"
      },
      {
        "codeType": "uppChannelCode",
        "code": "CHINAPAY",
        "codeDesc": "银联电子支付服务有限公司",
        "description": "通道信息"
      },
      {
        "codeType": "uppChannelCode",
        "code": "CMB",
        "codeDesc": "招商银行",
        "description": "通道信息"
      },
      {
        "codeType": "uppChannelCode",
        "code": "ICBC",
        "codeDesc": "中国工商银行",
        "description": "通道信息"
      },
      {
        "codeType": "uppChannelCode",
        "code": "SPDB",
        "codeDesc": "浦发银行",
        "description": "通道信息"
      },
      {
        "codeType": "uppBankTypeCode",
        "code": "ABC",
        "codeDesc": "中国农业银行",
        "description": "基础数据-机构信息（含银行和其他支付机构）"
      },
      {
        "codeType": "uppBankTypeCode",
        "code": "ALL",
        "codeDesc": "全部银行",
        "description": "基础数据-机构信息（含银行和其他支付机构）"
      },
      {
        "codeType": "uppBankTypeCode",
        "code": "BILL99",
        "codeDesc": "快钱",
        "description": "基础数据-机构信息（含银行和其他支付机构）"
      },
      {
        "codeType": "uppBankTypeCode",
        "code": "BOC",
        "codeDesc": "中国银行",
        "description": "基础数据-机构信息（含银行和其他支付机构）"
      },
      {
        "codeType": "uppBankTypeCode",
        "code": "CCB",
        "codeDesc": "中国建设银行",
        "description": "基础数据-机构信息（含银行和其他支付机构）"
      },
      {
        "codeType": "uppBankTypeCode",
        "code": "CEB",
        "codeDesc": "中国光大银行",
        "description": "基础数据-机构信息（含银行和其他支付机构）"
      },
      {
        "codeType": "uppBankTypeCode",
        "code": "CGB",
        "codeDesc": "广东发展银行",
        "description": "基础数据-机构信息（含银行和其他支付机构）"
      },
      {
        "codeType": "uppBankTypeCode",
        "code": "CHINAPAYSH",
        "codeDesc": "中国银联",
        "description": "基础数据-机构信息（含银行和其他支付机构）"
      },
      {
        "codeType": "uppBankTypeCode",
        "code": "CIB",
        "codeDesc": "中国兴业银行",
        "description": "基础数据-机构信息（含银行和其他支付机构）"
      },
      {
        "codeType": "uppBankTypeCode",
        "code": "CITIC",
        "codeDesc": "中信银行",
        "description": "基础数据-机构信息（含银行和其他支付机构）"
      },
      {
        "codeType": "uppBankTypeCode",
        "code": "CMB",
        "codeDesc": "中国招商银行",
        "description": "基础数据-机构信息（含银行和其他支付机构）"
      },
      {
        "codeType": "uppBankTypeCode",
        "code": "CMBC",
        "codeDesc": "中国民生银行",
        "description": "基础数据-机构信息（含银行和其他支付机构）"
      },
      {
        "codeType": "uppBankTypeCode",
        "code": "CMBCHINA",
        "codeDesc": "中国招商银行",
        "description": "基础数据-机构信息（含银行和其他支付机构）"
      },
      {
        "codeType": "uppBankTypeCode",
        "code": "ICBC",
        "codeDesc": "中国工商银行",
        "description": "基础数据-机构信息（含银行和其他支付机构）"
      },
      {
        "codeType": "uppBankTypeCode",
        "code": "PAB",
        "codeDesc": "平安银行",
        "description": "基础数据-机构信息（含银行和其他支付机构）"
      },
      {
        "codeType": "uppBankTypeCode",
        "code": "SPDB",
        "codeDesc": "上海浦东发展银行",
        "description": "基础数据-机构信息（含银行和其他支付机构）"
      },
      {
        "codeType": "uppBankCode",
        "code": "ABC",
        "codeDesc": "中国农业银行",
        "description": "基础数据-机构信息（只有银行）"
      },
      {
        "codeType": "uppBankCode",
        "code": "ALL",
        "codeDesc": "全部银行",
        "description": "基础数据-机构信息（只有银行）"
      },
      {
        "codeType": "uppBankCode",
        "code": "BOC",
        "codeDesc": "中国银行",
        "description": "基础数据-机构信息（只有银行）"
      },
      {
        "codeType": "uppBankCode",
        "code": "CCB",
        "codeDesc": "中国建设银行",
        "description": "基础数据-机构信息（只有银行）"
      },
      {
        "codeType": "uppBankCode",
        "code": "CEB",
        "codeDesc": "中国光大银行",
        "description": "基础数据-机构信息（只有银行）"
      },
      {
        "codeType": "uppBankCode",
        "code": "CGB",
        "codeDesc": "广东发展银行",
        "description": "基础数据-机构信息（只有银行）"
      },
      {
        "codeType": "uppBankCode",
        "code": "CIB",
        "codeDesc": "中国兴业银行",
        "description": "基础数据-机构信息（只有银行）"
      },
      {
        "codeType": "uppBankCode",
        "code": "CITIC",
        "codeDesc": "中信银行",
        "description": "基础数据-机构信息（只有银行）"
      },
      {
        "codeType": "uppBankCode",
        "code": "CMB",
        "codeDesc": "中国招商银行",
        "description": "基础数据-机构信息（只有银行）"
      },
      {
        "codeType": "uppBankCode",
        "code": "CMBC",
        "codeDesc": "中国民生银行",
        "description": "基础数据-机构信息（只有银行）"
      },
      {
        "codeType": "uppBankCode",
        "code": "CMBCHINA",
        "codeDesc": "中国招商银行",
        "description": "基础数据-机构信息（只有银行）"
      },
      {
        "codeType": "uppBankCode",
        "code": "ICBC",
        "codeDesc": "中国工商银行",
        "description": "基础数据-机构信息（只有银行）"
      },
      {
        "codeType": "uppBankCode",
        "code": "PAB",
        "codeDesc": "平安银行",
        "description": "基础数据-机构信息（只有银行）"
      },
      {
        "codeType": "uppBankCode",
        "code": "SPDB",
        "codeDesc": "上海浦东发展银行",
        "description": "基础数据-机构信息（只有银行）"
      },
      {
        "codeType": "uppAgenyCode",
        "code": "1",
        "codeDesc": "上海万达小额贷款有限公司",
        "description": "机构设置"
      },
      {
        "codeType": "uppAgenyCode",
        "code": "2",
        "codeDesc": "上海万达商业保理有限公司",
        "description": "机构设置"
      },
      {
        "codeType": "uppAgenyCode",
        "code": "3",
        "codeDesc": "万达财富投资基金有限公司",
        "description": "机构设置"
      },
      {
        "codeType": "uppChannelFeeCode",
        "code": "99BILL001",
        "codeDesc": "快钱对私代收业务收费标准",
        "description": "计费规则"
      },
      {
        "codeType": "uppChannelFeeCode",
        "code": "99BILL002",
        "codeDesc": "快钱对公代收业务收费标准",
        "description": "计费规则"
      },
      {
        "codeType": "uppChannelFeeCode",
        "code": "CHINAPAY001",
        "codeDesc": "ChinaPay对私代付业务收费标准",
        "description": "计费规则"
      },
      {
        "codeType": "uppChannelFeeCode",
        "code": "CHINAPAY002",
        "codeDesc": "ChinaPay对公代付业务收费标准",
        "description": "计费规则"
      },
      {
        "codeType": "uppChannelFeeCode",
        "code": "CHINAPAY003",
        "codeDesc": "ChinaPay代收业务收费标准",
        "description": "计费规则"
      },
      {
        "codeType": "uppChannelFeeCode",
        "code": "CMB001",
        "codeDesc": "招商银行对公代付实时到账业务收费标准",
        "description": "计费规则"
      }
    ]
  });
});

router.get('/web/v1/routes', function(req, res, next) {
  res.send({
    "respHeader": {
      "serviceName": null,
      "respMessage": "成功",
      "sessionId": "1462461678582",
      "reqId": "1471930736344",
      "respCode": "UPP-10000",
      "resMessageExt": null
    },
    "pageNum": 0,
    "pageSize": 20,
    "pages": 0,
    "total": 0,
    "uppRouteInfoDTO": []
  });
});

router.get('/web/v1/staticRoutes', function(req, res, next) {
  res.send({
    "respHeader": {
      "serviceName": null,
      "respMessage": "成功",
      "sessionId": "1462461678582",
      "reqId": "1471932340880",
      "respCode": "UPP-10000",
      "resMessageExt": null
    },
    "pageNum": 0,
    "pageSize": 20,
    "pages": 0,
    "total": 20,
    "queryParamList": [
      {
        "creator": "1",
        "modifier": "1",
        "createTime": 1471313135000,
        "lastModifiTime": 1471313138000,
        "uppStaticRouteId": 29,
        "uppAgencyCode": "1",
        "busType": 0,
        "productType": 0,
        "accountType": 0,
        "uppChannelCode": "BOC",
        "uppBankTypeCode": "ALL",
        "interfaceType": 0,
        "recordStatus": 0,
        "priorityCode": 0,
        "busTypeDesc": "信贷",
        "productTypeDesc": "收/付款",
        "accountDesc": "对私/对公",
        "channelTypeDesc": "中国银行",
        "statusDesc": "启用",
        "interfaceDesc": "单笔/批量",
        "bankTypeDesc": "全部银行",
        "priorityDesc": "",
        "uppStaticRouteMaintainId": null
      },
      {
        "creator": "1",
        "modifier": "2",
        "createTime": 1470981042000,
        "lastModifiTime": 1470983783000,
        "uppStaticRouteId": 28,
        "uppAgencyCode": "x",
        "busType": 1,
        "productType": 0,
        "accountType": 0,
        "uppChannelCode": "CHINAPAY",
        "uppBankTypeCode": "ABC",
        "interfaceType": 0,
        "recordStatus": 0,
        "priorityCode": 1,
        "busTypeDesc": "保理",
        "productTypeDesc": "收/付款",
        "accountDesc": "对私/对公",
        "channelTypeDesc": "银联电子支付服务有限公司",
        "statusDesc": "启用",
        "interfaceDesc": "单笔/批量",
        "bankTypeDesc": "中国农业银行",
        "priorityDesc": "高",
        "uppStaticRouteMaintainId": null
      },
      {
        "creator": "INIT",
        "modifier": "2",
        "createTime": 1470906712000,
        "lastModifiTime": 1470981290000,
        "uppStaticRouteId": 18,
        "uppAgencyCode": "1",
        "busType": 0,
        "productType": 0,
        "accountType": 0,
        "uppChannelCode": "CMB",
        "uppBankTypeCode": "CMBCHINA",
        "interfaceType": 0,
        "recordStatus": 0,
        "priorityCode": 1,
        "busTypeDesc": "信贷",
        "productTypeDesc": "收/付款",
        "accountDesc": "对私/对公",
        "channelTypeDesc": "招商银行",
        "statusDesc": "启用",
        "interfaceDesc": "单笔/批量",
        "bankTypeDesc": "中国招商银行",
        "priorityDesc": "高",
        "uppStaticRouteMaintainId": null
      },
      {
        "creator": "init",
        "modifier": "init",
        "createTime": 1470879181000,
        "lastModifiTime": 1470879187000,
        "uppStaticRouteId": 17,
        "uppAgencyCode": "1",
        "busType": 1,
        "productType": 0,
        "accountType": 0,
        "uppChannelCode": "CMB",
        "uppBankTypeCode": "ALL",
        "interfaceType": 0,
        "recordStatus": 0,
        "priorityCode": 0,
        "busTypeDesc": "保理",
        "productTypeDesc": "收/付款",
        "accountDesc": "对私/对公",
        "channelTypeDesc": "招商银行",
        "statusDesc": "启用",
        "interfaceDesc": "单笔/批量",
        "bankTypeDesc": "全部银行",
        "priorityDesc": "",
        "uppStaticRouteMaintainId": null
      },
      {
        "creator": "I",
        "modifier": "I",
        "createTime": 1470819673000,
        "lastModifiTime": 1470819676000,
        "uppStaticRouteId": 16,
        "uppAgencyCode": "1",
        "busType": 0,
        "productType": 0,
        "accountType": 0,
        "uppChannelCode": "99BILL",
        "uppBankTypeCode": "SPDB",
        "interfaceType": 0,
        "recordStatus": 0,
        "priorityCode": 0,
        "busTypeDesc": "信贷",
        "productTypeDesc": "收/付款",
        "accountDesc": "对私/对公",
        "channelTypeDesc": "快钱公司",
        "statusDesc": "启用",
        "interfaceDesc": "单笔/批量",
        "bankTypeDesc": "上海浦东发展银行",
        "priorityDesc": "",
        "uppStaticRouteMaintainId": null
      },
      {
        "creator": "init",
        "modifier": "2",
        "createTime": 1468400900000,
        "lastModifiTime": 1470386712000,
        "uppStaticRouteId": 1,
        "uppAgencyCode": "x",
        "busType": 0,
        "productType": 0,
        "accountType": 0,
        "uppChannelCode": "ICBC",
        "uppBankTypeCode": "ICBC",
        "interfaceType": 0,
        "recordStatus": 1,
        "priorityCode": 1,
        "busTypeDesc": "信贷",
        "productTypeDesc": "收/付款",
        "accountDesc": "对私/对公",
        "channelTypeDesc": "中国工商银行",
        "statusDesc": "注销/停用",
        "interfaceDesc": "单笔/批量",
        "bankTypeDesc": "中国工商银行",
        "priorityDesc": "高",
        "uppStaticRouteMaintainId": null
      },
      {
        "creator": "init",
        "modifier": "2",
        "createTime": 1468400900000,
        "lastModifiTime": 1470214954000,
        "uppStaticRouteId": 4,
        "uppAgencyCode": "1",
        "busType": 1,
        "productType": 0,
        "accountType": 0,
        "uppChannelCode": "CMB",
        "uppBankTypeCode": "CMBCHINA",
        "interfaceType": 0,
        "recordStatus": 0,
        "priorityCode": 0,
        "busTypeDesc": "保理",
        "productTypeDesc": "收/付款",
        "accountDesc": "对私/对公",
        "channelTypeDesc": "招商银行",
        "statusDesc": "启用",
        "interfaceDesc": "单笔/批量",
        "bankTypeDesc": "中国招商银行",
        "priorityDesc": "",
        "uppStaticRouteMaintainId": null
      },
      {
        "creator": "init",
        "modifier": "1",
        "createTime": 1468400900000,
        "lastModifiTime": 1470185637000,
        "uppStaticRouteId": 2,
        "uppAgencyCode": "1",
        "busType": 0,
        "productType": 0,
        "accountType": 0,
        "uppChannelCode": "BOC",
        "uppBankTypeCode": "BOC",
        "interfaceType": 0,
        "recordStatus": 0,
        "priorityCode": 0,
        "busTypeDesc": "信贷",
        "productTypeDesc": "收/付款",
        "accountDesc": "对私/对公",
        "channelTypeDesc": "中国银行",
        "statusDesc": "启用",
        "interfaceDesc": "单笔/批量",
        "bankTypeDesc": "中国银行",
        "priorityDesc": "",
        "uppStaticRouteMaintainId": null
      },
      {
        "creator": "init",
        "modifier": "1",
        "createTime": 1468400900000,
        "lastModifiTime": 1470120514000,
        "uppStaticRouteId": 9,
        "uppAgencyCode": "1",
        "busType": 0,
        "productType": 0,
        "accountType": 0,
        "uppChannelCode": "ICBC",
        "uppBankTypeCode": "ICBC",
        "interfaceType": 0,
        "recordStatus": 0,
        "priorityCode": 0,
        "busTypeDesc": "信贷",
        "productTypeDesc": "收/付款",
        "accountDesc": "对私/对公",
        "channelTypeDesc": "中国工商银行",
        "statusDesc": "启用",
        "interfaceDesc": "单笔/批量",
        "bankTypeDesc": "中国工商银行",
        "priorityDesc": "",
        "uppStaticRouteMaintainId": null
      },
      {
        "creator": "init",
        "modifier": "1",
        "createTime": 1468400900000,
        "lastModifiTime": 1470120512000,
        "uppStaticRouteId": 6,
        "uppAgencyCode": "x",
        "busType": 0,
        "productType": 2,
        "accountType": 0,
        "uppChannelCode": "CHINAPAY",
        "uppBankTypeCode": "ABC",
        "interfaceType": 1,
        "recordStatus": 1,
        "priorityCode": 1,
        "busTypeDesc": "信贷",
        "productTypeDesc": "扣款",
        "accountDesc": "对私/对公",
        "channelTypeDesc": "银联电子支付服务有限公司",
        "statusDesc": "注销/停用",
        "interfaceDesc": "单笔",
        "bankTypeDesc": "中国农业银行",
        "priorityDesc": "高",
        "uppStaticRouteMaintainId": null
      },
      {
        "creator": "init",
        "modifier": "1",
        "createTime": 1468400900000,
        "lastModifiTime": 1470120509000,
        "uppStaticRouteId": 15,
        "uppAgencyCode": "x",
        "busType": 0,
        "productType": 2,
        "accountType": 2,
        "uppChannelCode": "CCB",
        "uppBankTypeCode": "SPDB",
        "interfaceType": 2,
        "recordStatus": 1,
        "priorityCode": 1,
        "busTypeDesc": "信贷",
        "productTypeDesc": "扣款",
        "accountDesc": "对公",
        "channelTypeDesc": "中国建设银行",
        "statusDesc": "注销/停用",
        "interfaceDesc": "批量",
        "bankTypeDesc": "上海浦东发展银行",
        "priorityDesc": "高",
        "uppStaticRouteMaintainId": null
      },
      {
        "creator": "init",
        "modifier": "init",
        "createTime": 1468400900000,
        "lastModifiTime": 1468400900000,
        "uppStaticRouteId": 13,
        "uppAgencyCode": "x",
        "busType": 0,
        "productType": 2,
        "accountType": 0,
        "uppChannelCode": "CHINAPAY",
        "uppBankTypeCode": "CGB",
        "interfaceType": 1,
        "recordStatus": 0,
        "priorityCode": 1,
        "busTypeDesc": "信贷",
        "productTypeDesc": "扣款",
        "accountDesc": "对私/对公",
        "channelTypeDesc": "银联电子支付服务有限公司",
        "statusDesc": "启用",
        "interfaceDesc": "单笔",
        "bankTypeDesc": "广东发展银行",
        "priorityDesc": "高",
        "uppStaticRouteMaintainId": null
      },
      {
        "creator": "init",
        "modifier": "init",
        "createTime": 1468400900000,
        "lastModifiTime": 1468400900000,
        "uppStaticRouteId": 12,
        "uppAgencyCode": "x",
        "busType": 0,
        "productType": 2,
        "accountType": 0,
        "uppChannelCode": "CHINAPAY",
        "uppBankTypeCode": "CMBC",
        "interfaceType": 1,
        "recordStatus": 0,
        "priorityCode": 1,
        "busTypeDesc": "信贷",
        "productTypeDesc": "扣款",
        "accountDesc": "对私/对公",
        "channelTypeDesc": "银联电子支付服务有限公司",
        "statusDesc": "启用",
        "interfaceDesc": "单笔",
        "bankTypeDesc": "中国民生银行",
        "priorityDesc": "高",
        "uppStaticRouteMaintainId": null
      },
      {
        "creator": "init",
        "modifier": "init",
        "createTime": 1468400900000,
        "lastModifiTime": 1468400900000,
        "uppStaticRouteId": 10,
        "uppAgencyCode": "x",
        "busType": 0,
        "productType": 2,
        "accountType": 0,
        "uppChannelCode": "CHINAPAY",
        "uppBankTypeCode": "CIB",
        "interfaceType": 1,
        "recordStatus": 0,
        "priorityCode": 1,
        "busTypeDesc": "信贷",
        "productTypeDesc": "扣款",
        "accountDesc": "对私/对公",
        "channelTypeDesc": "银联电子支付服务有限公司",
        "statusDesc": "启用",
        "interfaceDesc": "单笔",
        "bankTypeDesc": "中国兴业银行",
        "priorityDesc": "高",
        "uppStaticRouteMaintainId": null
      },
      {
        "creator": "init",
        "modifier": "init",
        "createTime": 1468400900000,
        "lastModifiTime": 1468400900000,
        "uppStaticRouteId": 8,
        "uppAgencyCode": "x",
        "busType": 0,
        "productType": 2,
        "accountType": 0,
        "uppChannelCode": "CHINAPAY",
        "uppBankTypeCode": "PAB",
        "interfaceType": 1,
        "recordStatus": 0,
        "priorityCode": 1,
        "busTypeDesc": "信贷",
        "productTypeDesc": "扣款",
        "accountDesc": "对私/对公",
        "channelTypeDesc": "银联电子支付服务有限公司",
        "statusDesc": "启用",
        "interfaceDesc": "单笔",
        "bankTypeDesc": "平安银行",
        "priorityDesc": "高",
        "uppStaticRouteMaintainId": null
      },
      {
        "creator": "init",
        "modifier": "init",
        "createTime": 1468400900000,
        "lastModifiTime": 1468400900000,
        "uppStaticRouteId": 7,
        "uppAgencyCode": "x",
        "busType": 0,
        "productType": 2,
        "accountType": 0,
        "uppChannelCode": "CHINAPAY",
        "uppBankTypeCode": "CEB",
        "interfaceType": 1,
        "recordStatus": 0,
        "priorityCode": 1,
        "busTypeDesc": "信贷",
        "productTypeDesc": "扣款",
        "accountDesc": "对私/对公",
        "channelTypeDesc": "银联电子支付服务有限公司",
        "statusDesc": "启用",
        "interfaceDesc": "单笔",
        "bankTypeDesc": "中国光大银行",
        "priorityDesc": "高",
        "uppStaticRouteMaintainId": null
      },
      {
        "creator": "init",
        "modifier": "init",
        "createTime": 1468400900000,
        "lastModifiTime": 1468400900000,
        "uppStaticRouteId": 14,
        "uppAgencyCode": "X",
        "busType": 0,
        "productType": 0,
        "accountType": 0,
        "uppChannelCode": "99BILL",
        "uppBankTypeCode": "CEB",
        "interfaceType": 0,
        "recordStatus": 0,
        "priorityCode": 0,
        "busTypeDesc": "信贷",
        "productTypeDesc": "收/付款",
        "accountDesc": "对私/对公",
        "channelTypeDesc": "快钱公司",
        "statusDesc": "启用",
        "interfaceDesc": "单笔/批量",
        "bankTypeDesc": "中国光大银行",
        "priorityDesc": "",
        "uppStaticRouteMaintainId": null
      },
      {
        "creator": "init",
        "modifier": "init",
        "createTime": 1468400900000,
        "lastModifiTime": 1468400900000,
        "uppStaticRouteId": 11,
        "uppAgencyCode": "x",
        "busType": 0,
        "productType": 0,
        "accountType": 0,
        "uppChannelCode": "CHINAPAY",
        "uppBankTypeCode": "CITIC",
        "interfaceType": 0,
        "recordStatus": 0,
        "priorityCode": 1,
        "busTypeDesc": "信贷",
        "productTypeDesc": "收/付款",
        "accountDesc": "对私/对公",
        "channelTypeDesc": "银联电子支付服务有限公司",
        "statusDesc": "启用",
        "interfaceDesc": "单笔/批量",
        "bankTypeDesc": "中信银行",
        "priorityDesc": "高",
        "uppStaticRouteMaintainId": null
      },
      {
        "creator": "init",
        "modifier": "init",
        "createTime": 1468400900000,
        "lastModifiTime": 1468400900000,
        "uppStaticRouteId": 5,
        "uppAgencyCode": "x",
        "busType": 0,
        "productType": 0,
        "accountType": 0,
        "uppChannelCode": "CHINAPAY",
        "uppBankTypeCode": "ALL",
        "interfaceType": 0,
        "recordStatus": 0,
        "priorityCode": 1,
        "busTypeDesc": "信贷",
        "productTypeDesc": "收/付款",
        "accountDesc": "对私/对公",
        "channelTypeDesc": "银联电子支付服务有限公司",
        "statusDesc": "启用",
        "interfaceDesc": "单笔/批量",
        "bankTypeDesc": "全部银行",
        "priorityDesc": "高",
        "uppStaticRouteMaintainId": null
      },
      {
        "creator": "init",
        "modifier": "init",
        "createTime": 1468400900000,
        "lastModifiTime": 1468400900000,
        "uppStaticRouteId": 3,
        "uppAgencyCode": "1",
        "busType": 0,
        "productType": 0,
        "accountType": 0,
        "uppChannelCode": "SPDB",
        "uppBankTypeCode": "SPDB",
        "interfaceType": 0,
        "recordStatus": 0,
        "priorityCode": 0,
        "busTypeDesc": "信贷",
        "productTypeDesc": "收/付款",
        "accountDesc": "对私/对公",
        "channelTypeDesc": "浦发银行",
        "statusDesc": "启用",
        "interfaceDesc": "单笔/批量",
        "bankTypeDesc": "上海浦东发展银行",
        "priorityDesc": "",
        "uppStaticRouteMaintainId": null
      }
    ]
  });
});

router.get('/web/v1/accounts', function(req, res, next) {
  res.send({
    "respHeader": {
      "serviceName": null,
      "respMessage": "成功",
      "sessionId": "1462461678582",
      "reqId": "1471933171380",
      "respCode": "UPP-10000",
      "resMessageExt": null
    },
    "pageNum": 0,
    "pageSize": 20,
    "pages": 0,
    "total": 13,
    "uppAccountList": [
      {
        "creator": "init",
        "modifier": "init",
        "createTime": 1470623890000,
        "lastModifiTime": 1470623894000,
        "uppAccountId": 13,
        "accountNo": "808080211388216",
        "accountName": "对公付款商户号",
        "accountNameEn": null,
        "currency": "CNY",
        "accountType": 0,
        "uppAgencyCode": "1",
        "busType": 0,
        "productType": 0,
        "accountStatus": 0,
        "province": "上海",
        "city": "上海",
        "country": "中国",
        "uppChannelCode": "CHINAPAY",
        "uppBankTypeCode": "CHINAPAYSH",
        "bankName": "银联",
        "openDate": 1470585600000,
        "branchCode": null,
        "branchUniteCode": null,
        "cnapsCode": null,
        "accountProperty": 0,
        "contractNo": "",
        "accountTypeDesc": "对私/对公",
        "busTypeDesc": "信贷",
        "productTypeDesc": "收/付款",
        "accountStatusDesc": "正常",
        "accountPropertyDesc": "",
        "uppChannelName": "银联电子支付服务有限公司"
      },
      {
        "creator": "init",
        "modifier": "init",
        "createTime": 1470295522000,
        "lastModifiTime": 1470295526000,
        "uppAccountId": 12,
        "accountNo": "808080211388216",
        "accountName": "单笔代扣商户号",
        "accountNameEn": null,
        "currency": "CNY",
        "accountType": 0,
        "uppAgencyCode": "1",
        "busType": 0,
        "productType": 0,
        "accountStatus": 0,
        "province": "上海",
        "city": "上海",
        "country": "中国",
        "uppChannelCode": "CHINAPAY",
        "uppBankTypeCode": "CHINAPAYSH",
        "bankName": "银联",
        "openDate": 1470240000000,
        "branchCode": null,
        "branchUniteCode": null,
        "cnapsCode": null,
        "accountProperty": 0,
        "contractNo": "",
        "accountTypeDesc": "对私/对公",
        "busTypeDesc": "信贷",
        "productTypeDesc": "收/付款",
        "accountStatusDesc": "正常",
        "accountPropertyDesc": "",
        "uppChannelName": "银联电子支付服务有限公司"
      },
      {
        "creator": "init",
        "modifier": "INIT",
        "createTime": 1470294421000,
        "lastModifiTime": 1470294426000,
        "uppAccountId": 11,
        "accountNo": "591902896910101",
        "accountName": "银企直连专用账户11",
        "accountNameEn": null,
        "currency": "CNY",
        "accountType": 0,
        "uppAgencyCode": "1",
        "busType": 1,
        "productType": 0,
        "accountStatus": 0,
        "province": "福建",
        "city": "福州市",
        "country": "中国",
        "uppChannelCode": "CMB",
        "uppBankTypeCode": "CMBCHINA",
        "bankName": "招商银行",
        "openDate": 1470240000000,
        "branchCode": null,
        "branchUniteCode": null,
        "cnapsCode": null,
        "accountProperty": 0,
        "contractNo": "",
        "accountTypeDesc": "对私/对公",
        "busTypeDesc": "保理",
        "productTypeDesc": "收/付款",
        "accountStatusDesc": "正常",
        "accountPropertyDesc": "",
        "uppChannelName": "招商银行"
      },
      {
        "creator": "init",
        "modifier": "init",
        "createTime": 1468400900000,
        "lastModifiTime": 1468400900000,
        "uppAccountId": 10,
        "accountNo": "591902896910101",
        "accountName": "银企直连专用账户11",
        "accountNameEn": "",
        "currency": "CNY",
        "accountType": 0,
        "uppAgencyCode": "1",
        "busType": 1,
        "productType": 0,
        "accountStatus": 0,
        "province": "福建省",
        "city": "福州市",
        "country": "中国",
        "uppChannelCode": "CMB",
        "uppBankTypeCode": "CMBCHINA",
        "bankName": "中国招商银行",
        "openDate": 1468339200000,
        "branchCode": "",
        "branchUniteCode": "",
        "cnapsCode": "",
        "accountProperty": 0,
        "contractNo": "",
        "accountTypeDesc": "对私/对公",
        "busTypeDesc": "保理",
        "productTypeDesc": "收/付款",
        "accountStatusDesc": "正常",
        "accountPropertyDesc": "",
        "uppChannelName": "招商银行"
      },
      {
        "creator": "init",
        "modifier": "init",
        "createTime": 1468400900000,
        "lastModifiTime": 1468400900000,
        "uppAccountId": 9,
        "accountNo": "10012174867",
        "accountName": "代扣商户号",
        "accountNameEn": "",
        "currency": "CNY",
        "accountType": 0,
        "uppAgencyCode": "1",
        "busType": 0,
        "productType": 2,
        "accountStatus": 0,
        "province": "上海",
        "city": "上海",
        "country": "中国",
        "uppChannelCode": "99BILL",
        "uppBankTypeCode": "BILL99",
        "bankName": "快钱",
        "openDate": 1468339200000,
        "branchCode": "",
        "branchUniteCode": "",
        "cnapsCode": "",
        "accountProperty": 1,
        "contractNo": "",
        "accountTypeDesc": "对私/对公",
        "busTypeDesc": "信贷",
        "productTypeDesc": "扣款",
        "accountStatusDesc": "正常",
        "accountPropertyDesc": "",
        "uppChannelName": "快钱公司"
      },
      {
        "creator": "init",
        "modifier": "init",
        "createTime": 1468400900000,
        "lastModifiTime": 1468400900000,
        "uppAccountId": 8,
        "accountNo": "10012168367",
        "accountName": "代付商户号",
        "accountNameEn": "",
        "currency": "CNY",
        "accountType": 0,
        "uppAgencyCode": "1",
        "busType": 0,
        "productType": 1,
        "accountStatus": 0,
        "province": "上海",
        "city": "上海",
        "country": "中国",
        "uppChannelCode": "99BILL",
        "uppBankTypeCode": "BILL99",
        "bankName": "快钱",
        "openDate": 1468339200000,
        "branchCode": "",
        "branchUniteCode": "",
        "cnapsCode": "",
        "accountProperty": 2,
        "contractNo": "",
        "accountTypeDesc": "对私/对公",
        "busTypeDesc": "信贷",
        "productTypeDesc": "付款",
        "accountStatusDesc": "正常",
        "accountPropertyDesc": "",
        "uppChannelName": "快钱公司"
      },
      {
        "creator": "init",
        "modifier": "init",
        "createTime": 1468400900000,
        "lastModifiTime": 1468400900000,
        "uppAccountId": 7,
        "accountNo": "808080211388216",
        "accountName": "对私代付商户号",
        "accountNameEn": "",
        "currency": "CNY",
        "accountType": 1,
        "uppAgencyCode": "1",
        "busType": 0,
        "productType": 1,
        "accountStatus": 0,
        "province": "上海",
        "city": "上海",
        "country": "中国",
        "uppChannelCode": "CHINAPAY",
        "uppBankTypeCode": "CHINAPAYSH",
        "bankName": "银联",
        "openDate": 1468339200000,
        "branchCode": "",
        "branchUniteCode": "",
        "cnapsCode": "",
        "accountProperty": 2,
        "contractNo": "",
        "accountTypeDesc": "对私",
        "busTypeDesc": "信贷",
        "productTypeDesc": "付款",
        "accountStatusDesc": "正常",
        "accountPropertyDesc": "",
        "uppChannelName": "银联电子支付服务有限公司"
      },
      {
        "creator": "init",
        "modifier": "init",
        "createTime": 1468400900000,
        "lastModifiTime": 1468400900000,
        "uppAccountId": 6,
        "accountNo": "808080211388216",
        "accountName": "对公代付商户号",
        "accountNameEn": "",
        "currency": "CNY",
        "accountType": 2,
        "uppAgencyCode": "1",
        "busType": 0,
        "productType": 1,
        "accountStatus": 0,
        "province": "上海",
        "city": "上海",
        "country": "中国",
        "uppChannelCode": "CHINAPAY",
        "uppBankTypeCode": "CHINAPAYSH",
        "bankName": "银联",
        "openDate": 1468339200000,
        "branchCode": "",
        "branchUniteCode": "",
        "cnapsCode": "",
        "accountProperty": 2,
        "contractNo": "",
        "accountTypeDesc": "对公",
        "busTypeDesc": "信贷",
        "productTypeDesc": "付款",
        "accountStatusDesc": "正常",
        "accountPropertyDesc": "",
        "uppChannelName": "银联电子支付服务有限公司"
      },
      {
        "creator": "init",
        "modifier": "init",
        "createTime": 1468400900000,
        "lastModifiTime": 1468400900000,
        "uppAccountId": 5,
        "accountNo": "808080211388214",
        "accountName": "批量代扣商户号",
        "accountNameEn": "",
        "currency": "CNY",
        "accountType": 0,
        "uppAgencyCode": "1",
        "busType": 0,
        "productType": 2,
        "accountStatus": 0,
        "province": "上海",
        "city": "上海",
        "country": "中国",
        "uppChannelCode": "CHINAPAY",
        "uppBankTypeCode": "CHINAPAYSH",
        "bankName": "银联",
        "openDate": 1468339200000,
        "branchCode": "",
        "branchUniteCode": "",
        "cnapsCode": "",
        "accountProperty": 1,
        "contractNo": "",
        "accountTypeDesc": "对私/对公",
        "busTypeDesc": "信贷",
        "productTypeDesc": "扣款",
        "accountStatusDesc": "正常",
        "accountPropertyDesc": "",
        "uppChannelName": "银联电子支付服务有限公司"
      },
      {
        "creator": "init",
        "modifier": "init",
        "createTime": 1468400900000,
        "lastModifiTime": 1468400900000,
        "uppAccountId": 4,
        "accountNo": "591902896910101",
        "accountName": "银企直连专用账户11",
        "accountNameEn": "",
        "currency": "CNY",
        "accountType": 0,
        "uppAgencyCode": "1",
        "busType": 1,
        "productType": 0,
        "accountStatus": 0,
        "province": "福建省",
        "city": "福州市",
        "country": "中国",
        "uppChannelCode": "CMB",
        "uppBankTypeCode": "CMBCHINA",
        "bankName": "中国招商银行",
        "openDate": 1468339200000,
        "branchCode": "",
        "branchUniteCode": "",
        "cnapsCode": "",
        "accountProperty": 0,
        "contractNo": "",
        "accountTypeDesc": "对私/对公",
        "busTypeDesc": "保理",
        "productTypeDesc": "收/付款",
        "accountStatusDesc": "正常",
        "accountPropertyDesc": "",
        "uppChannelName": "招商银行"
      },
      {
        "creator": "init",
        "modifier": "init",
        "createTime": 1468400900000,
        "lastModifiTime": 1468400900000,
        "uppAccountId": 3,
        "accountNo": "6224080400151",
        "accountName": "浦发2000046452",
        "accountNameEn": "",
        "currency": "CNY",
        "accountType": 0,
        "uppAgencyCode": "1",
        "busType": 0,
        "productType": 0,
        "accountStatus": 0,
        "province": "上海",
        "city": "上海",
        "country": "中国",
        "uppChannelCode": "SPDB",
        "uppBankTypeCode": "SPDB",
        "bankName": "上海浦东发展银行",
        "openDate": 1468339200000,
        "branchCode": "",
        "branchUniteCode": "",
        "cnapsCode": "",
        "accountProperty": 0,
        "contractNo": "",
        "accountTypeDesc": "对私/对公",
        "busTypeDesc": "信贷",
        "productTypeDesc": "收/付款",
        "accountStatusDesc": "正常",
        "accountPropertyDesc": "",
        "uppChannelName": "浦发银行"
      },
      {
        "creator": "init",
        "modifier": "init",
        "createTime": 1468400900000,
        "lastModifiTime": 1468400900000,
        "uppAccountId": 2,
        "accountNo": "329856083051",
        "accountName": "微软中国",
        "accountNameEn": "",
        "currency": "CNY",
        "accountType": 0,
        "uppAgencyCode": "1",
        "busType": 0,
        "productType": 0,
        "accountStatus": 0,
        "province": "北京",
        "city": "北京",
        "country": "中国",
        "uppChannelCode": "BOC",
        "uppBankTypeCode": "BOC",
        "bankName": "中国银行",
        "openDate": 1468339200000,
        "branchCode": "40142",
        "branchUniteCode": "40142",
        "cnapsCode": "",
        "accountProperty": 0,
        "contractNo": "",
        "accountTypeDesc": "对私/对公",
        "busTypeDesc": "信贷",
        "productTypeDesc": "收/付款",
        "accountStatusDesc": "正常",
        "accountPropertyDesc": "",
        "uppChannelName": "中国银行"
      },
      {
        "creator": "init",
        "modifier": "init",
        "createTime": 1468400900000,
        "lastModifiTime": 1468400900000,
        "uppAccountId": 1,
        "accountNo": "0200004519000100297",
        "accountName": "随登馈碗冯表坎贬削率咕",
        "accountNameEn": "",
        "currency": "CNY",
        "accountType": 0,
        "uppAgencyCode": "1",
        "busType": 0,
        "productType": 0,
        "accountStatus": 0,
        "province": "上海",
        "city": "上海",
        "country": "中国",
        "uppChannelCode": "ICBC",
        "uppBankTypeCode": "ICBC",
        "bankName": "中国工商银行",
        "openDate": 1468339200000,
        "branchCode": "",
        "branchUniteCode": "",
        "cnapsCode": "",
        "accountProperty": 0,
        "contractNo": "",
        "accountTypeDesc": "对私/对公",
        "busTypeDesc": "信贷",
        "productTypeDesc": "收/付款",
        "accountStatusDesc": "正常",
        "accountPropertyDesc": "",
        "uppChannelName": "中国工商银行"
      }
    ]
  });
});

router.get('/web/v1/channelAbilitys', function(req, res, next) {
  res.send({
    "respHeader": {
      "serviceName": null,
      "respMessage": "成功",
      "sessionId": "1462461678582",
      "reqId": "1471933500767",
      "respCode": "UPP-10000",
      "resMessageExt": null
    },
    "pageNum": 0,
    "pageSize": 20,
    "pages": 0,
    "total": 31,
    "uppChannelAbilityList": [
      {
        "creator": "IMD",
        "modifier": "INF",
        "createTime": 1471500869000,
        "lastModifiTime": 1471500874000,
        "uppChannelAbilityId": 38,
        "uppAgencyCode": "1",
        "busType": 0,
        "productType": 0,
        "accountType": 0,
        "uppChannelCode": "SPDB",
        "uppBankTypeCode": "SPDB",
        "interfaceType": 0,
        "maxamtEachTrans": 40000,
        "maxamtEachDay": 80000,
        "windowType": null,
        "windowStart": -28800000,
        "windowEnd": -28800000,
        "recordStatus": 0,
        "uppChannelName": "浦发银行",
        "uppBankTypeName": "上海浦东发展银行",
        "accountTypeDesc": "对私/对公",
        "interfaceTypeDesc": "单笔/批量",
        "busTypeDesc": "信贷",
        "productTypeDesc": "收/付款",
        "recordStatusDesc": "启用",
        "uppChannelAbilityMaintainId": null
      },
      {
        "creator": "INT",
        "modifier": "INT",
        "createTime": 1471491300000,
        "lastModifiTime": 1471491303000,
        "uppChannelAbilityId": 36,
        "uppAgencyCode": "1",
        "busType": 0,
        "productType": 0,
        "accountType": 0,
        "uppChannelCode": "ICBC",
        "uppBankTypeCode": "ICBC",
        "interfaceType": 0,
        "maxamtEachTrans": 400000,
        "maxamtEachDay": 30000000,
        "windowType": null,
        "windowStart": -28800000,
        "windowEnd": -28800000,
        "recordStatus": 0,
        "uppChannelName": "中国工商银行",
        "uppBankTypeName": "中国工商银行",
        "accountTypeDesc": "对私/对公",
        "interfaceTypeDesc": "单笔/批量",
        "busTypeDesc": "信贷",
        "productTypeDesc": "收/付款",
        "recordStatusDesc": "启用",
        "uppChannelAbilityMaintainId": null
      },
      {
        "creator": "1",
        "modifier": "1",
        "createTime": 1471313082000,
        "lastModifiTime": 1471313086000,
        "uppChannelAbilityId": 35,
        "uppAgencyCode": "1",
        "busType": 0,
        "productType": 0,
        "accountType": 0,
        "uppChannelCode": "BOC",
        "uppBankTypeCode": "ALL",
        "interfaceType": 0,
        "maxamtEachTrans": 30000,
        "maxamtEachDay": 10000000,
        "windowType": null,
        "windowStart": -28800000,
        "windowEnd": -28800000,
        "recordStatus": 0,
        "uppChannelName": "中国银行",
        "uppBankTypeName": "全部银行",
        "accountTypeDesc": "对私/对公",
        "interfaceTypeDesc": "单笔/批量",
        "busTypeDesc": "信贷",
        "productTypeDesc": "收/付款",
        "recordStatusDesc": "启用",
        "uppChannelAbilityMaintainId": null
      },
      {
        "creator": "INIT",
        "modifier": "INIT",
        "createTime": 1470822861000,
        "lastModifiTime": 1470822865000,
        "uppChannelAbilityId": 34,
        "uppAgencyCode": "1",
        "busType": 1,
        "productType": 0,
        "accountType": 0,
        "uppChannelCode": "CMB",
        "uppBankTypeCode": "ALL",
        "interfaceType": 0,
        "maxamtEachTrans": 30000,
        "maxamtEachDay": 10000000,
        "windowType": null,
        "windowStart": -28800000,
        "windowEnd": -28800000,
        "recordStatus": 0,
        "uppChannelName": "招商银行",
        "uppBankTypeName": "全部银行",
        "accountTypeDesc": "对私/对公",
        "interfaceTypeDesc": "单笔/批量",
        "busTypeDesc": "保理",
        "productTypeDesc": "收/付款",
        "recordStatusDesc": "启用",
        "uppChannelAbilityMaintainId": null
      },
      {
        "creator": "init",
        "modifier": "2",
        "createTime": 1468400900000,
        "lastModifiTime": 1470821212000,
        "uppChannelAbilityId": 11,
        "uppAgencyCode": "3",
        "busType": 0,
        "productType": 0,
        "accountType": 0,
        "uppChannelCode": "CHINAPAY",
        "uppBankTypeCode": "ALL",
        "interfaceType": 0,
        "maxamtEachTrans": 56000,
        "maxamtEachDay": 100000,
        "windowType": null,
        "windowStart": -28800000,
        "windowEnd": -28800000,
        "recordStatus": 0,
        "uppChannelName": "银联电子支付服务有限公司",
        "uppBankTypeName": "全部银行",
        "accountTypeDesc": "对私/对公",
        "interfaceTypeDesc": "单笔/批量",
        "busTypeDesc": "信贷",
        "productTypeDesc": "收/付款",
        "recordStatusDesc": "启用",
        "uppChannelAbilityMaintainId": null
      },
      {
        "creator": "12",
        "modifier": "123",
        "createTime": 1470741719000,
        "lastModifiTime": 1470741723000,
        "uppChannelAbilityId": 27,
        "uppAgencyCode": "1",
        "busType": 0,
        "productType": 0,
        "accountType": 0,
        "uppChannelCode": "BOC",
        "uppBankTypeCode": "BOC",
        "interfaceType": 0,
        "maxamtEachTrans": 50000,
        "maxamtEachDay": 1000000,
        "windowType": null,
        "windowStart": -28800000,
        "windowEnd": -28800000,
        "recordStatus": 0,
        "uppChannelName": "中国银行",
        "uppBankTypeName": "中国银行",
        "accountTypeDesc": "对私/对公",
        "interfaceTypeDesc": "单笔/批量",
        "busTypeDesc": "信贷",
        "productTypeDesc": "收/付款",
        "recordStatusDesc": "启用",
        "uppChannelAbilityMaintainId": null
      },
      {
        "creator": "init",
        "modifier": "init",
        "createTime": 1468400900000,
        "lastModifiTime": 1468400900000,
        "uppChannelAbilityId": 5,
        "uppAgencyCode": "1",
        "busType": 0,
        "productType": 2,
        "accountType": 1,
        "uppChannelCode": "CHINAPAY",
        "uppBankTypeCode": "PAB",
        "interfaceType": 1,
        "maxamtEachTrans": 999999,
        "maxamtEachDay": 5000000,
        "windowType": null,
        "windowStart": -28800000,
        "windowEnd": -28800000,
        "recordStatus": 0,
        "uppChannelName": "银联电子支付服务有限公司",
        "uppBankTypeName": "平安银行",
        "accountTypeDesc": "对私",
        "interfaceTypeDesc": "单笔",
        "busTypeDesc": "信贷",
        "productTypeDesc": "扣款",
        "recordStatusDesc": "启用",
        "uppChannelAbilityMaintainId": null
      },
      {
        "creator": "init",
        "modifier": "init",
        "createTime": 1468400900000,
        "lastModifiTime": 1468400900000,
        "uppChannelAbilityId": 2,
        "uppAgencyCode": "1",
        "busType": 0,
        "productType": 2,
        "accountType": 1,
        "uppChannelCode": "CHINAPAY",
        "uppBankTypeCode": "ABC",
        "interfaceType": 1,
        "maxamtEachTrans": 1000000,
        "maxamtEachDay": 1000000,
        "windowType": null,
        "windowStart": -28800000,
        "windowEnd": -28800000,
        "recordStatus": 0,
        "uppChannelName": "银联电子支付服务有限公司",
        "uppBankTypeName": "中国农业银行",
        "accountTypeDesc": "对私",
        "interfaceTypeDesc": "单笔",
        "busTypeDesc": "信贷",
        "productTypeDesc": "扣款",
        "recordStatusDesc": "启用",
        "uppChannelAbilityMaintainId": null
      },
      {
        "creator": "init",
        "modifier": "init",
        "createTime": 1468400900000,
        "lastModifiTime": 1468400900000,
        "uppChannelAbilityId": 26,
        "uppAgencyCode": "3",
        "busType": 0,
        "productType": 2,
        "accountType": 1,
        "uppChannelCode": "CHINAPAY",
        "uppBankTypeCode": "CGB",
        "interfaceType": 1,
        "maxamtEachTrans": 1500000,
        "maxamtEachDay": 30000000,
        "windowType": null,
        "windowStart": -28800000,
        "windowEnd": -28800000,
        "recordStatus": 0,
        "uppChannelName": "银联电子支付服务有限公司",
        "uppBankTypeName": "广东发展银行",
        "accountTypeDesc": "对私",
        "interfaceTypeDesc": "单笔",
        "busTypeDesc": "信贷",
        "productTypeDesc": "扣款",
        "recordStatusDesc": "启用",
        "uppChannelAbilityMaintainId": null
      },
      {
        "creator": "init",
        "modifier": "init",
        "createTime": 1468400900000,
        "lastModifiTime": 1468400900000,
        "uppChannelAbilityId": 16,
        "uppAgencyCode": "1",
        "busType": 1,
        "productType": 1,
        "accountType": 0,
        "uppChannelCode": "CMB",
        "uppBankTypeCode": "CMBCHINA",
        "interfaceType": 0,
        "maxamtEachTrans": 5000,
        "maxamtEachDay": 10000,
        "windowType": null,
        "windowStart": -28800000,
        "windowEnd": -28800000,
        "recordStatus": 0,
        "uppChannelName": "招商银行",
        "uppBankTypeName": "中国招商银行",
        "accountTypeDesc": "对私/对公",
        "interfaceTypeDesc": "单笔/批量",
        "busTypeDesc": "保理",
        "productTypeDesc": "付款",
        "recordStatusDesc": "启用",
        "uppChannelAbilityMaintainId": null
      },
      {
        "creator": "init",
        "modifier": "init",
        "createTime": 1468400900000,
        "lastModifiTime": 1468400900000,
        "uppChannelAbilityId": 22,
        "uppAgencyCode": "3",
        "busType": 0,
        "productType": 2,
        "accountType": 1,
        "uppChannelCode": "CHINAPAY",
        "uppBankTypeCode": "CCB",
        "interfaceType": 1,
        "maxamtEachTrans": 500000,
        "maxamtEachDay": 500000,
        "windowType": null,
        "windowStart": -28800000,
        "windowEnd": -28800000,
        "recordStatus": 0,
        "uppChannelName": "银联电子支付服务有限公司",
        "uppBankTypeName": "中国建设银行",
        "accountTypeDesc": "对私",
        "interfaceTypeDesc": "单笔",
        "busTypeDesc": "信贷",
        "productTypeDesc": "扣款",
        "recordStatusDesc": "启用",
        "uppChannelAbilityMaintainId": null
      },
      {
        "creator": "init",
        "modifier": "init",
        "createTime": 1468400900000,
        "lastModifiTime": 1468400900000,
        "uppChannelAbilityId": 8,
        "uppAgencyCode": "1",
        "busType": 0,
        "productType": 0,
        "accountType": 0,
        "uppChannelCode": "CHINAPAY",
        "uppBankTypeCode": "CITIC",
        "interfaceType": 1,
        "maxamtEachTrans": 1500000,
        "maxamtEachDay": 30000000,
        "windowType": null,
        "windowStart": -28800000,
        "windowEnd": -28800000,
        "recordStatus": 0,
        "uppChannelName": "银联电子支付服务有限公司",
        "uppBankTypeName": "中信银行",
        "accountTypeDesc": "对私/对公",
        "interfaceTypeDesc": "单笔",
        "busTypeDesc": "信贷",
        "productTypeDesc": "收/付款",
        "recordStatusDesc": "启用",
        "uppChannelAbilityMaintainId": null
      },
      {
        "creator": "init",
        "modifier": "init",
        "createTime": 1468400900000,
        "lastModifiTime": 1468400900000,
        "uppChannelAbilityId": 19,
        "uppAgencyCode": "3",
        "busType": 0,
        "productType": 2,
        "accountType": 1,
        "uppChannelCode": "CHINAPAY",
        "uppBankTypeCode": "BOC",
        "interfaceType": 1,
        "maxamtEachTrans": 50000,
        "maxamtEachDay": 1000000,
        "windowType": null,
        "windowStart": -28800000,
        "windowEnd": -28800000,
        "recordStatus": 0,
        "uppChannelName": "银联电子支付服务有限公司",
        "uppBankTypeName": "中国银行",
        "accountTypeDesc": "对私",
        "interfaceTypeDesc": "单笔",
        "busTypeDesc": "信贷",
        "productTypeDesc": "扣款",
        "recordStatusDesc": "启用",
        "uppChannelAbilityMaintainId": null
      },
      {
        "creator": "init",
        "modifier": "init",
        "createTime": 1468400900000,
        "lastModifiTime": 1468400900000,
        "uppChannelAbilityId": 10,
        "uppAgencyCode": "1",
        "busType": 0,
        "productType": 2,
        "accountType": 1,
        "uppChannelCode": "CHINAPAY",
        "uppBankTypeCode": "CGB",
        "interfaceType": 1,
        "maxamtEachTrans": 1500000,
        "maxamtEachDay": 30000000,
        "windowType": null,
        "windowStart": -28800000,
        "windowEnd": -28800000,
        "recordStatus": 0,
        "uppChannelName": "银联电子支付服务有限公司",
        "uppBankTypeName": "广东发展银行",
        "accountTypeDesc": "对私",
        "interfaceTypeDesc": "单笔",
        "busTypeDesc": "信贷",
        "productTypeDesc": "扣款",
        "recordStatusDesc": "启用",
        "uppChannelAbilityMaintainId": null
      },
      {
        "creator": "init",
        "modifier": "init",
        "createTime": 1468400900000,
        "lastModifiTime": 1468400900000,
        "uppChannelAbilityId": 6,
        "uppAgencyCode": "1",
        "busType": 0,
        "productType": 2,
        "accountType": 1,
        "uppChannelCode": "CHINAPAY",
        "uppBankTypeCode": "CCB",
        "interfaceType": 1,
        "maxamtEachTrans": 500000,
        "maxamtEachDay": 500000,
        "windowType": null,
        "windowStart": -28800000,
        "windowEnd": -28800000,
        "recordStatus": 0,
        "uppChannelName": "银联电子支付服务有限公司",
        "uppBankTypeName": "中国建设银行",
        "accountTypeDesc": "对私",
        "interfaceTypeDesc": "单笔",
        "busTypeDesc": "信贷",
        "productTypeDesc": "扣款",
        "recordStatusDesc": "启用",
        "uppChannelAbilityMaintainId": null
      },
      {
        "creator": "init",
        "modifier": "init",
        "createTime": 1468400900000,
        "lastModifiTime": 1468400900000,
        "uppChannelAbilityId": 14,
        "uppAgencyCode": "1",
        "busType": 0,
        "productType": 0,
        "accountType": 0,
        "uppChannelCode": "99BILL",
        "uppBankTypeCode": "CEB",
        "interfaceType": 0,
        "maxamtEachTrans": 100000,
        "maxamtEachDay": 2000000,
        "windowType": null,
        "windowStart": -28800000,
        "windowEnd": -28800000,
        "recordStatus": 0,
        "uppChannelName": "快钱公司",
        "uppBankTypeName": "中国光大银行",
        "accountTypeDesc": "对私/对公",
        "interfaceTypeDesc": "单笔/批量",
        "busTypeDesc": "信贷",
        "productTypeDesc": "收/付款",
        "recordStatusDesc": "启用",
        "uppChannelAbilityMaintainId": null
      },
      {
        "creator": "init",
        "modifier": "init",
        "createTime": 1468400900000,
        "lastModifiTime": 1468400900000,
        "uppChannelAbilityId": 3,
        "uppAgencyCode": "1",
        "busType": 0,
        "productType": 2,
        "accountType": 1,
        "uppChannelCode": "CHINAPAY",
        "uppBankTypeCode": "BOC",
        "interfaceType": 1,
        "maxamtEachTrans": 50000,
        "maxamtEachDay": 1000000,
        "windowType": null,
        "windowStart": -28800000,
        "windowEnd": -28800000,
        "recordStatus": 0,
        "uppChannelName": "银联电子支付服务有限公司",
        "uppBankTypeName": "中国银行",
        "accountTypeDesc": "对私",
        "interfaceTypeDesc": "单笔",
        "busTypeDesc": "信贷",
        "productTypeDesc": "扣款",
        "recordStatusDesc": "启用",
        "uppChannelAbilityMaintainId": null
      },
      {
        "creator": "init",
        "modifier": "init",
        "createTime": 1468400900000,
        "lastModifiTime": 1468400900000,
        "uppChannelAbilityId": 15,
        "uppAgencyCode": "1",
        "busType": 0,
        "productType": 2,
        "accountType": 2,
        "uppChannelCode": "99BILL",
        "uppBankTypeCode": "PAB",
        "interfaceType": 2,
        "maxamtEachTrans": 500000,
        "maxamtEachDay": 30000000,
        "windowType": null,
        "windowStart": -28800000,
        "windowEnd": -28800000,
        "recordStatus": 0,
        "uppChannelName": "快钱公司",
        "uppBankTypeName": "平安银行",
        "accountTypeDesc": "对公",
        "interfaceTypeDesc": "批量",
        "busTypeDesc": "信贷",
        "productTypeDesc": "扣款",
        "recordStatusDesc": "启用",
        "uppChannelAbilityMaintainId": null
      },
      {
        "creator": "init",
        "modifier": "init",
        "createTime": 1468400900000,
        "lastModifiTime": 1468400900000,
        "uppChannelAbilityId": 1,
        "uppAgencyCode": "1",
        "busType": 0,
        "productType": 2,
        "accountType": 1,
        "uppChannelCode": "CHINAPAY",
        "uppBankTypeCode": "ICBC",
        "interfaceType": 0,
        "maxamtEachTrans": 50000,
        "maxamtEachDay": 50000,
        "windowType": null,
        "windowStart": -28800000,
        "windowEnd": -28800000,
        "recordStatus": 0,
        "uppChannelName": "银联电子支付服务有限公司",
        "uppBankTypeName": "中国工商银行",
        "accountTypeDesc": "对私",
        "interfaceTypeDesc": "单笔/批量",
        "busTypeDesc": "信贷",
        "productTypeDesc": "扣款",
        "recordStatusDesc": "启用",
        "uppChannelAbilityMaintainId": null
      },
      {
        "creator": "init",
        "modifier": "init",
        "createTime": 1468400900000,
        "lastModifiTime": 1468400900000,
        "uppChannelAbilityId": 23,
        "uppAgencyCode": "3",
        "busType": 0,
        "productType": 2,
        "accountType": 1,
        "uppChannelCode": "CHINAPAY",
        "uppBankTypeCode": "CIB",
        "interfaceType": 1,
        "maxamtEachTrans": 50000,
        "maxamtEachDay": 50000,
        "windowType": null,
        "windowStart": -28800000,
        "windowEnd": -28800000,
        "recordStatus": 0,
        "uppChannelName": "银联电子支付服务有限公司",
        "uppBankTypeName": "中国兴业银行",
        "accountTypeDesc": "对私",
        "interfaceTypeDesc": "单笔",
        "busTypeDesc": "信贷",
        "productTypeDesc": "扣款",
        "recordStatusDesc": "启用",
        "uppChannelAbilityMaintainId": null
      }
    ]
  });
});

router.get('/web/v1/channelFees', function(req, res, next) {
  res.send({
    "respHeader": {
      "serviceName": null,
      "respMessage": "成功",
      "sessionId": "1462461678582",
      "reqId": "1471933580074",
      "respCode": "UPP-10000",
      "resMessageExt": null
    },
    "pageNum": 0,
    "pageSize": 20,
    "pages": 0,
    "total": 6,
    "uppChannelFeeList": [
      {
        "creator": "init",
        "modifier": "2",
        "createTime": 1468400900000,
        "lastModifiTime": 1470981288000,
        "uppChannelFeeCode": "99BILL001",
        "uppAgencyCode": "1",
        "busType": 0,
        "uppChannelCode": "99BILL",
        "uppChannelFeeName": "快钱对私代收业务收费标准",
        "recordStatus": 0,
        "uppChannelName": "快钱公司",
        "applyStatus": null,
        "recordStatusDesc": "启用",
        "busTypeDesc": "信贷",
        "uppChannelFeeDetailDTOList": null,
        "uppChannelFeeMaintainId": null
      },
      {
        "creator": "init",
        "modifier": "init",
        "createTime": 1468400900000,
        "lastModifiTime": 1468400900000,
        "uppChannelFeeCode": "CHINAPAY001",
        "uppAgencyCode": "1",
        "busType": 0,
        "uppChannelCode": "CHINAPAY",
        "uppChannelFeeName": "ChinaPay对私代付业务收费标准",
        "recordStatus": 0,
        "uppChannelName": "银联电子支付服务有限公司",
        "applyStatus": null,
        "recordStatusDesc": "启用",
        "busTypeDesc": "信贷",
        "uppChannelFeeDetailDTOList": null,
        "uppChannelFeeMaintainId": null
      },
      {
        "creator": "init",
        "modifier": "init",
        "createTime": 1468400900000,
        "lastModifiTime": 1468400900000,
        "uppChannelFeeCode": "CMB001",
        "uppAgencyCode": "2",
        "busType": 1,
        "uppChannelCode": "CMB",
        "uppChannelFeeName": "招商银行对公代付实时到账业务收费标准",
        "recordStatus": 0,
        "uppChannelName": "招商银行",
        "applyStatus": null,
        "recordStatusDesc": "启用",
        "busTypeDesc": "保理",
        "uppChannelFeeDetailDTOList": null,
        "uppChannelFeeMaintainId": null
      },
      {
        "creator": "init",
        "modifier": "init",
        "createTime": 1468400900000,
        "lastModifiTime": 1468400900000,
        "uppChannelFeeCode": "CHINAPAY002",
        "uppAgencyCode": "1",
        "busType": 0,
        "uppChannelCode": "CHINAPAY",
        "uppChannelFeeName": "ChinaPay对公代付业务收费标准",
        "recordStatus": 0,
        "uppChannelName": "银联电子支付服务有限公司",
        "applyStatus": null,
        "recordStatusDesc": "启用",
        "busTypeDesc": "信贷",
        "uppChannelFeeDetailDTOList": null,
        "uppChannelFeeMaintainId": null
      },
      {
        "creator": "init",
        "modifier": "init",
        "createTime": 1468400900000,
        "lastModifiTime": 1468400900000,
        "uppChannelFeeCode": "99BILL002",
        "uppAgencyCode": "1",
        "busType": 0,
        "uppChannelCode": "99BILL",
        "uppChannelFeeName": "快钱对公代收业务收费标准",
        "recordStatus": 0,
        "uppChannelName": "快钱公司",
        "applyStatus": null,
        "recordStatusDesc": "启用",
        "busTypeDesc": "信贷",
        "uppChannelFeeDetailDTOList": null,
        "uppChannelFeeMaintainId": null
      },
      {
        "creator": "init",
        "modifier": "init",
        "createTime": 1468400900000,
        "lastModifiTime": 1468400900000,
        "uppChannelFeeCode": "CHINAPAY003",
        "uppAgencyCode": "1",
        "busType": 0,
        "uppChannelCode": "CHINAPAY",
        "uppChannelFeeName": "ChinaPay代收业务收费标准",
        "recordStatus": 0,
        "uppChannelName": "银联电子支付服务有限公司",
        "applyStatus": null,
        "recordStatusDesc": "启用",
        "busTypeDesc": "信贷",
        "uppChannelFeeDetailDTOList": null,
        "uppChannelFeeMaintainId": null
      }
    ]
  });
});

router.get('/web/v1/channelAbility', function(req, res, next) {
  res.send({
    "respHeader": {
      "serviceName": null,
      "respMessage": "成功",
      "sessionId": "1462461678582",
      "reqId": "1471934854887",
      "respCode": "UPP-10000",
      "resMessageExt": null
    },
    "uppChannelAbility": {
      "creator": "IMD",
      "modifier": "INF",
      "createTime": 1471500869000,
      "lastModifiTime": 1471500874000,
      "uppChannelAbilityId": 38,
      "uppAgencyCode": "1",
      "busType": 0,
      "productType": 0,
      "accountType": 0,
      "uppChannelCode": "SPDB",
      "uppBankTypeCode": "SPDB",
      "interfaceType": 0,
      "maxamtEachTrans": 40000,
      "maxamtEachDay": 80000,
      "windowType": null,
      "windowStart": -28800000,
      "windowEnd": -28800000,
      "recordStatus": 0,
      "uppChannelName": "浦发银行",
      "uppBankTypeName": "上海浦东发展银行",
      "accountTypeDesc": "对私/对公",
      "interfaceTypeDesc": "单笔/批量",
      "busTypeDesc": "信贷",
      "productTypeDesc": "收/付款",
      "recordStatusDesc": "启用",
      "uppChannelAbilityMaintainId": null
    },
    "uppChannelAbilityList": null
  });
});

router.get('/web/v1/channelFee', function(req, res, next) {
  res.send({
    "respHeader": {
      "serviceName": null,
      "respMessage": "成功",
      "sessionId": "1462461678582",
      "reqId": "1471934960107",
      "respCode": "UPP-10000",
      "resMessageExt": null
    },
    "uppChannelFeeDTO": {
      "creator": "init",
      "modifier": "2",
      "createTime": 1468400900000,
      "lastModifiTime": 1470981288000,
      "uppChannelFeeCode": "99BILL001",
      "uppAgencyCode": "1",
      "busType": 0,
      "uppChannelCode": "99BILL",
      "uppChannelFeeName": "快钱对私代收业务收费标准",
      "recordStatus": 0,
      "uppChannelName": "快钱公司",
      "applyStatus": null,
      "recordStatusDesc": "启用",
      "busTypeDesc": "信贷",
      "uppChannelFeeDetailDTOList": [
        {
          "creator": null,
          "modifier": null,
          "createTime": null,
          "lastModifiTime": null,
          "uppChannelFeeDetailId": null,
          "uppChannelFeeCode": "99BILL001",
          "cardType": 0,
          "isSameCity": null,
          "amountStart": 0,
          "amountEnd": 1000000000000,
          "feeType": 0,
          "caculateType": 0,
          "feeAmount": 2,
          "minBypercent": null,
          "maxBypercent": null,
          "cardTypeDesc": "本行同城及异地/他行",
          "feeTypeDesc": "手续费",
          "caculateTypeDesc": "按笔收费",
          "amountStartSection": 0,
          "amountEndSection": 9
        }
      ],
      "uppChannelFeeMaintainId": null
    }
  });
});

router.get('/web/v1/staticRoute', function(req, res, next) {
  res.send({
    "respHeader": {
      "serviceName": null,
      "respMessage": "成功",
      "sessionId": "1462461678582",
      "reqId": "1471935105806",
      "respCode": "UPP-10000",
      "resMessageExt": null
    },
    "uppStaticRouteDTO": {
      "creator": "1",
      "modifier": "1",
      "createTime": 1471313135000,
      "lastModifiTime": 1471313138000,
      "uppStaticRouteId": 29,
      "uppAgencyCode": "1",
      "busType": 0,
      "productType": 0,
      "accountType": 0,
      "uppChannelCode": "BOC",
      "uppBankTypeCode": "ALL",
      "interfaceType": 0,
      "recordStatus": 0,
      "priorityCode": 0,
      "busTypeDesc": "信贷",
      "productTypeDesc": "收/付款",
      "accountDesc": "对私/对公",
      "channelTypeDesc": "中国银行",
      "statusDesc": "启用",
      "interfaceDesc": "单笔/批量",
      "bankTypeDesc": "全部银行",
      "priorityDesc": "",
      "uppStaticRouteMaintainId": null
    }
  });
});

module.exports = router;
